Resolve #1052
pyvista/pyvista pull request #1194
Opened 2021-02-20 01:53 UTC by tkoyama010

### Overview

Resolve #1052

 

### Details

As far as I see, all we have to fix is only `DataObject` (https://github.com/pyvista/pyvista/issues/1052#issuecomment-775566180).

2021-02-20 17:47 UTC, akaszynski requested changes
We're writing to the user path during testing.  Unit tests are all done in the isolated `tmpdir` environment to avoid any conflicts with existing files.  If (for whatever reason) the user had a `~/tmp.vtk` file, we'd overwrite it.

Best approach I think is to simply not test this functionality within our unit tests.  I don't like it, but it's better than writing temp files to user paths.

2021-02-20 18:05 UTC, tkoyama010 commented
@akaszynski 

> We're writing to the user path during testing. Unit tests are all done in the isolated tmpdir environment to avoid any conflicts with existing files. If (for whatever reason) the user had a `~/tmp.vtk` file, we'd overwrite it.
> Best approach I think is to simply not test this functionality within our unit tests. I don't like it, but it's better than writing temp files to user paths.

I don't like either. However, it is not good to write in the user path as you say :-( I will delete the test. Thank you for reivew.

2021-02-20 18:07 UTC, tkoyama010 commented on tests/test_grid.py
> +    assert isinstance(grid, pyvista.UnstructuredGrid)
```suggestion
```

2021-02-20 18:07 UTC, tkoyama010 commented on tests/test_polydata.py
> +    assert mesh.points.shape == sphere.points.shape
```suggestion
```

2021-02-21 00:42 UTC, akaszynski approved these changes
Thanks for fixing that.  At least it's hit by code coverage.

2021-02-21 01:01 UTC, merged