Closes #1849
pyvista/pyvista pull request #1853
Opened 2021-11-25 18:49 UTC by Carlosbogo

Changes the color of the plotted points in [Using Python lists or tuples](https://github.com/pyvista/pyvista/issues/1849#:~:text=Using%20Python%20Lists%20or%20Tuples) to improve their visibility.

2021-11-25 18:56 UTC, adeak commented
Welcome, and thanks for the PR! :)

I've taken the liberty of retitling your PR. You can add the "closes ..." message to the PR comment itself, that's how github will know to link this PR with the issue.

2021-11-25 18:58 UTC, adeak reviewed
Just a small styling suggestion (see [PEP 8](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements)).

2021-11-25 18:58 UTC, adeak commented on doc/user-guide/data_model.rst
> +   >>> mesh.plot(show_bounds=True, color = 'red', cpos='xy', point_size=20)
```suggestion
   >>> mesh.plot(show_bounds=True, color='red', cpos='xy', point_size=20)
```

2021-11-25 19:25 UTC, tkoyama010 requested changes
@Carlosbogo Thank you for PR. There is more figure which color of point is white in [Using Python Lists or Tuples](https://dev.pyvista.org/user-guide/data_model.html#using-python-lists-or-tuples). Could you search and also fix it too?

2021-11-26 20:20 UTC, banesullivan commented
@pyvista/developers, I'm concerned this was an issue at all. Why isn't this using the default `document` theme where `color` defaults to `'tan'`?

2021-11-26 20:49 UTC, adeak commented
Any chance that this is related to the "opacity-containing figures are broken" problem? Although [that](https://github.com/pyvista/pyvista/issues/1355) seems fixed now...

![Screenshot from 2021-11-26 21-48-10](https://user-images.githubusercontent.com/17914410/143635635-fec3cd29-f667-4cf9-8a22-02bd26df6b2b.png)

Interactively the point markers are semi-transparent, that's what gave me the idea.

2021-12-24 15:47 UTC, akaszynski commented
> Actually, now I see that this is only broken on dev.pyvista.org, but not docs.pyvista.org. Much better.

The actual issue is due to overwriting the global theme and is resolved in #1963. The documentation at docs.pyvista.org were built using `make -C doc phtml`, and the thread writing the data model section did not evaluate the docstrings of `theme.py` and therefore did not have its theme changed.

2021-12-24 15:47 UTC, closed without merging