Add integrate_data filter
pyvista/pyvista pull request #2790
Opened 2022-06-14 13:59 UTC by MatthewFlamm

### Overview

Closes #2789 .  Adds ability to integrate data in a dataset including area or volume.

### Details

The vtk class [vtkIntegrateAttributes](https://vtk.org/doc/nightly/html/classvtkIntegrateAttributes.html) includes a `SetDivideAllCellDataByVolume()` method, but I have deliberately chosen not to implement it and in fact have explicitly turned it off.  When enabled, _only_ the integrated cell data is divided by the area or volume.  This could be confusing, and it is straightforward for the user to implement themselves.

The return from this filter is a bit weird at first, an `UnstructuredGrid` with 1 point and 1 cell. I considered returning a dict, e.g. {"data": 99.1, "Area": 2.45}. But given that we can have name clashes between point and cell data arrays, we'd have to return two dicts.  So I have chosen to keep the default vtk behavior, and tried to explain this multiple times in the documentation and examples.

2022-06-14 15:16 UTC, MatthewFlamm commented
I intended to add to the gallery example one that uses a volume, but I ran out of implementation scheme.  This might be a good 'first issue' that we can add.

2022-06-15 09:09 UTC, akaszynski commented on pyvista/core/filters/data_set.py
> +         There is only 1 point/cell, so access the only value.
```suggestion
        There is only 1 point/cell, so access the only value.
```

2022-06-15 09:46 UTC, tkoyama010 requested changes
Thank you for adding this.

2022-06-15 09:46 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +        Area or volume also provided in point data.
```suggestion
        Area or volume is also provided in point data.
```

2022-06-15 09:46 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +        """Integrate point and cell data.
It would be good to explicit the algorithm of the integral method. Can we specify the type of algorithm?

2022-06-15 10:13 UTC, tkoyama010 approved these changes
LGTM

2022-06-16 08:44 UTC, merged