Add notes regarding optional dependencies
pyvista/pyvista pull request #2826
Opened 2022-06-19 20:10 UTC by akaszynski

Resolve #2688 by adding notes on the optional dependencies.

Also includes `ipyvtklink` and `pythreejs` as optional dependencies to both `[all]` and the new `[jupyter]` sections. Given the rise and popularity of `jupyterlab`, I think we should have this included.

2022-06-19 20:58 UTC, tkoyama010 requested changes

2022-06-19 20:58 UTC, tkoyama010 commented on doc/getting-started/installation.rst
> +PyVista includes several optional dependencies for visualization and file IO, including:
```suggestion
PyVista includes several optional dependencies for visualization and files IO, including:
```

2022-06-19 20:58 UTC, tkoyama010 commented on doc/getting-started/installation.rst
> +To install all the additional packages that extend pyvista, install using
```suggestion
To install all the additional packages that extend PyVista, install using
```

2022-06-20 00:39 UTC, akaszynski commented on doc/getting-started/installation.rst
> +PyVista includes several optional dependencies for visualization and file IO, including:
```suggestion
PyVista includes several optional dependencies for visualization and reading a variety of additional file formats, including:
```

2022-06-20 00:40 UTC, tkoyama010 approved these changes
LGTM

2022-06-21 06:50 UTC, merged