Implement taubin smoothing
pyvista/pyvista pull request #2829
Opened 2022-06-20 00:38 UTC by akaszynski

Resolves #2814 by implementing Taubin smoothing.

```py
import pyvista as pv
from pyvista import examples
mesh = examples.download_foot_bones().subdivide(2)
smoothed_mesh = mesh.smooth_taubin()
pl = pv.Plotter(shape=(1, 2))
_ = pl.add_mesh(mesh)
pl.add_text('Original Mesh')
pl.subplot(0, 1)
_ = pl.add_mesh(smoothed_mesh)
pl.add_text('Smoothed Mesh')
pl.show()
```

![tmp](https://user-images.githubusercontent.com/11981631/174506744-b13e7088-62d0-4344-9ee9-05e00d883d0d.png)

2022-06-20 03:24 UTC, akaszynski commented on pyvista/core/filters/poly_data.py
> +        convergence=0.0,
```suggestion
```

2022-06-20 03:25 UTC, akaszynski commented on pyvista/core/filters/poly_data.py
> +            the original coordinate frame. This defaults to ``False``
```suggestion
            the original coordinate frame. This defaults to ``False``.
```

2022-06-20 03:50 UTC, tkoyama010 requested changes

2022-06-20 03:50 UTC, tkoyama010 commented on pyvista/core/filters/poly_data.py
> +        more akin to low pass filter where undesirable high frequency features
```suggestion
        more akin to a low pass filter where undesirable high frequency features
```

2022-06-20 03:50 UTC, tkoyama010 commented on pyvista/core/filters/poly_data.py
> +            The passband value for the windowed sinc filter. This should be
I didn't know [sinc filter](https://en.wikipedia.org/wiki/Sinc_filter).

2022-06-20 03:50 UTC, tkoyama010 commented on tests/test_filters.py
>      assert np.any(smooth.points)
Will the points increase if we use `smooth_taubin`? If so, we can add it to the test.

2022-06-24 21:51 UTC, tkoyama010 approved these changes
LGTM

2022-06-24 21:52 UTC, tkoyama010 commented
It requires https://github.com/pyvista/pyvista/pull/2853 to merge.

2022-06-25 20:49 UTC, akaszynski commented
> It requires #2853 to merge.

Going to go without that following our 24H rule.

2022-06-25 22:49 UTC, merged