Ensure data remains a shallow copy when added to plotter
pyvista/pyvista pull request #2888
Opened 2022-06-28 00:07 UTC by akaszynski

Resolve #2461 by ensuring that a shallow copied dataset remains shallow when added to a plotter.

2022-06-28 00:53 UTC, banesullivan submitted a review, later dismissed

2022-06-28 03:19 UTC, tkoyama010 requested changes

2022-06-28 03:19 UTC, tkoyama010 commented on tests/test_plotter.py
> +    sphere['numbers'] *= -1
```suggestion
    sphere['numbers'] *= -1  # sphere2 'numbers' are also modified after adding to Plotter.  (See  issue #2461)
```

2022-06-29 15:33 UTC, banesullivan approved these changes
Merging when CI comes back green

2022-06-29 15:34 UTC, banesullivan approved these changes

2022-06-29 18:45 UTC, tkoyama010 approved these changes

2022-06-29 18:45 UTC, merged