Handle invalid theme on init
pyvista/pyvista pull request #2917
Opened 2022-06-30 03:07 UTC by akaszynski

As noted in #2910, if an invalid theme is set in `PYVISTA_PLOT_THEME`, you will simply be unable to `import pyvista` and potentially get a cryptic error.

This PR fixes this behavior by warning rather than raising.

2022-06-30 17:13 UTC, banesullivan approved these changes

2022-06-30 23:52 UTC, tkoyama010 requested changes
Thanks for adding this.

2022-06-30 23:52 UTC, tkoyama010 commented on pyvista/utilities/misc.py
> +def _set_plot_theme_from_env():
```suggestion
def _set_plot_theme_from_env():
    """Set plot theme from an enviroment variable."""
```

2022-07-01 01:25 UTC, akaszynski commented on pyvista/utilities/misc.py
> +    """Set plot theme from an enviroment variable."""
```suggestion
    """Set plot theme from an environment variable."""
```

2022-07-01 01:33 UTC, tkoyama010 approved these changes
LGTM

2022-07-02 13:52 UTC, merged