Add constrained triangulation example
pyvista/pyvista pull request #3448
Opened 2022-10-11 20:07 UTC by akaszynski

The docstring of the `delaunay_2d` filter is missing a constrained tesselation example.

```py
import pyvista as pv

squar = pv.Polygon(n_sides=4, radius=8, fill=False).rotate_z(45, inplace=False)
circ0 = pv.Polygon(center=(2, 3, 0), n_sides=30, radius=1)
circ1 = pv.Polygon(center=(-2, -3, 0), n_sides=30, radius=1)
comb = circ0 + circ1 + squar
tess = comb.delaunay_2d(edge_source=comb)
tess.plot(cpos='xy')
```

![tmp](https://user-images.githubusercontent.com/11981631/195188321-443bc1c9-d4e6-40ba-b2c9-d979f3367b95.png)

---

As a bonus, converts `optional` to `default` in the docstring of this method.

2022-10-11 22:07 UTC, banesullivan submitted a review, later dismissed
Would be great to plot `comb` before the triangulation to give more context

Otherwise, nice addition!

2022-10-11 23:28 UTC, akaszynski commented
Suddenly seeing instability with:
```
reading sources... [ 19%] api/plotting/charts/_autosummary/pyvista.plotting.charts.Axis
Fatal Python error: Segmentation fault

Current thread 0x00007f837d79b740 (most recent call first):
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 4328 in _run_image_filter
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 4389 in get_image_depth
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 6093 in show
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/charts.py", line 1438 in show
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/charts.py", line 113 in mem_sub
  File "<string>", line 4 in <module>
  File "/home/runner/work/pyvista/pyvista/pyvista/ext/plot_directive.py", line 328 in _run_code
  File "/home/runner/work/pyvista/pyvista/pyvista/ext/plot_directive.py", line 367 in render_figures
  File "/home/runner/work/pyvista/pyvista/pyvista/ext/plot_directive.py", line 502 in run
  File "/home/runner/work/pyvista/pyvista/pyvista/ext/plot_directive.py", line 173 in run
```

Looks like a charts issue, but it's unclear what's causing it.

2022-10-12 06:47 UTC, tkoyama010 requested changes
Thanks for adding this. I am excited about this example.

2022-10-12 06:47 UTC, tkoyama010 commented on pyvista/core/filters/poly_data.py
> +        >>> tess.plot(cpos='xy')
```suggestion
        >>> tess.plot(cpos='xy', show_edges=True)
```

2022-10-12 23:13 UTC, akaszynski commented
Going ahead and merging this. Would like to get the release process out soon and changes have been implemented. Thanks @banesullivan and @tkoyama010 for your reviews!

2022-10-12 23:13 UTC, merged