Fix interactive updates
pyvista/pyvista pull request #3617
Opened 2022-11-17 21:44 UTC by dcbr

### Overview

Fix interactive updates, resolves #3560, resolves #3584.
Also fixes an error when closing the plotter window while chart interaction was enabled.

### Details

- #3245 introduced the line `self.interactor = None` in the `terminate_app` method. The `on_timer` callback only needs a `TerminateApp()` call (to resume execution from a blocking `ProcessEvents` or `Start` call), without actually destroying the interactor itself. This PR moves the `self.interactor = None` line to the `close` method instead. I hope this is fine, but it would be nice if the contributors of #3245 could chime in :)
- I also tried to improve the documentation a bit for the related "interactive update" code.
- Another change in #3245 is to call the `remove_observers` method from the active `_style_class` in the `close` method. While this works for all interaction classes created from the `_style_factory`, it does not work for the `vtkContextInteractorStyle` class used for chart interaction. This caused an error while closing the plotter window when this chart interaction is enabled. My quick fix here was to first disable chart interaction before further cleaning up.

2022-11-20 09:29 UTC, dcbr commented
So, the timer test fails on Linux for VTK<9.2 because the ProcessEvents method did not properly process timer events, this was fixed in [!8560](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8560) and released in VTK9.2. I have no access to a Mac OS system, so not sure what is causing the fails there. If it is using another interactor than `vtkXRenderWindowInteractor` it might have the same bug that is still unfixed in VTK9.2.
Other than that this PR is ready for review now.

2022-11-25 17:52 UTC, dcbr commented
@pyvista/developers this is ready for review.

The codecov complaints are not relevant IMO:

- Lines 1950-1954 and 5904 in `plotting.py` have always been there and are now only executed for older VTK versions.
- The mentioned lines in `render_window_interactor.py` are all tested in `test_timer` but skipped on some (older) VTK versions (maybe that's why there is a complaint?).

2022-11-26 04:52 UTC, tkoyama010 requested changes

2022-11-26 04:52 UTC, tkoyama010 commented on tests/test_render_window_interactor.py
> +    # which is the default for offscreen rendering)
```suggestion
    # Create a normal interactor from the offscreen plotter (not generic,
    # which is the default for offscreen rendering)
```

2022-11-26 04:52 UTC, tkoyama010 commented on tests/test_render_window_interactor.py
> +    # Test one-shot timer (only fired once for extended duration)
```suggestion
    # Test one-shot timer (only fired once for the extended duration)
```

2022-11-30 19:09 UTC, tkoyama010 approved these changes

2022-12-13 08:55 UTC, dcbr commented
@pyvista/developers could we move along with this?

2022-12-13 16:04 UTC, banesullivan commented
Hey, yes, I will merge this today. I assigned myself as review to double check this issues you were seeing on Mac.

This is fairly critical so it needs to merge

2022-12-13 16:33 UTC, banesullivan approved these changes
Things are working on my M2 and Intel Macs. I was able to reproduce the error on `main` and no longer able to on this branch.

I'm merging `main` into this to run CI one more time and ensure passing then will merge.

2022-12-14 15:07 UTC, merged