Change unresolved BasePlotter intersphinx refs to Plotter
pyvista/pyvista pull request #3642
Opened 2022-11-23 22:43 UTC by adeak

I noticed that `BasePlotter` method references don't resolve in the docs:

![screenshot from outside plotting.py showing red, unresolved pyvista.BasePlotter.subplot() reference](https://user-images.githubusercontent.com/17914410/203657996-3ad3cbfc-b525-4f7e-8b06-c6c2f06d4733.png)

![screenshot from within plotting.py showing red, unresolved BasePlotter.update reference](https://user-images.githubusercontent.com/17914410/203658017-b121cce6-0903-4fb3-a8f9-66a65b19ff6c.png)

Switching the references to `Plotter` should fix the issue (existing links referring to `pyvista.Plotter`, or within `plotting.py` to `Plotter`, get resolved correctly).

2022-11-23 22:44 UTC, adeak commented on examples/02-plot/multi-window.py
> +# the :func:`pyvista.Plotter.subplot` method.
This block looked like it was supposed to be outside the code blocks. I've added the break header, but we'll have to check the doc build artifact to make sure the result doesn't look weird in some way (I'm mostly concerned by having a `Plotter` created in the first block but shown in the second).

2022-11-23 22:47 UTC, tkoyama010 requested changes

2022-11-23 22:47 UTC, tkoyama010 commented on examples/02-plot/multi-window.py
> +# ``shape=(2, 2)``. Use the :func:`pyvista.Plotter.subplot` function to
```suggestion
# ``shape=(2, 2)``. Use the :func:`pyvista.Plotter.subplot` method to
```

2022-11-23 22:49 UTC, adeak commented on examples/02-plot/multi-window.py
> +# ``shape=(2, 2)``. Use the :func:`pyvista.Plotter.subplot` function to
Good catch, thanks!

2022-11-23 23:13 UTC, adeak commented on examples/02-plot/multi-window.py
> +# the :func:`pyvista.Plotter.subplot` method.
The original change broke the doc build so I've made this into a proper comment with no sphinx markup.

2022-11-24 00:59 UTC, tkoyama010 approved these changes
LGTM except for comments about block.

2022-11-30 12:10 UTC, merged