Add "Powered by NumFOCUS" badge
pyvista/pyvista pull request #4049
Opened 2023-02-22 09:51 UTC by tkoyama010

### Overview

I found the "Powered by NumFOCUS" badge when looking at other projects and will add it.

 

### Details

- None

2023-02-22 15:55 UTC, banesullivan requested changes
Considering that PyVista is only an "Affiliated Project" at this time (as opposed to a "Sponsored Project"), I think we should choose different phrasing than "Powered by". We should look to other affiliated projects for guidance on the phrases and/or potential badges to re-use

2023-03-04 00:51 UTC, akaszynski commented
I looked at https://numfocus.org/sponsored-projects/affiliated-projects and after checking ~5 I didn't see any with this badge. Agree with @banesullivan, let's put this on hold.

I'd be happy with a "Affiliated with Numfocus" badge.

2023-03-07 16:55 UTC, akaszynski approved these changes
LGTM. Thanks @tkoyama010!

2023-03-08 03:44 UTC, merged

2023-03-14 15:35 UTC, banesullivan commented on README.rst
> +   :target: https://numfocus.org
I'm curious why this was merged with the "Sponsored by" language still present? This should be changed to:

```suggestion
.. | Affiliated with NumFOCUS| image:: https://img.shields.io/badge/affiliated-NumFOCUS-orange.svg?style=flat&colorA=E1523D&colorB=007D8A
   :target: https://numfocus.org
```