Make DataSet.cell a generator
pyvista/pyvista pull request #4082
Opened 2023-03-02 21:32 UTC by MatthewFlamm

### Overview

Make `DataSet.cell` a generator to prevent `mesh.cell[0]` usage.  It is recommended in the docstring to use this for `for cell in mesh.cell:` usage and `mesh.get_cell(0)` for single cell access.

### Details

Closes #3971.

Tries to ameliorate name clash with `UnstructuredGrid.cells` by putting in a See Also section.  I'm still concerned about this name clash however.  It will be more natural to use `for cell in mesh.cells:`, so I expect a lot of problems here.  Should we add a `cell_array` method to match `vtkCellArray` and then deprecate `cells`?  Once the original meaning of `cells` has been removed, we can move `cell` -> `cells`.  While technically avoiding breaking change, it will probably take years to accomplish and will be confusing in its own right.

2023-03-02 21:39 UTC, MatthewFlamm commented
We should consider whether we should do the same for `Cell.faces` and `Cell.edges`, i.e. make them generators.  It is MUCH less of a time hit for a one off, but I think being consistent has advantages.  Also, there must be someone out there would want to optimize their code by not forming the entire list, e.g. loop over faces, make a check and exit the for loop.  I'm +1 for this, but I think there was some conversation on the original PR that favored the list usage, so this is up for discussion.

2023-03-02 22:31 UTC, darikg commented
`mesh.iter_cells()` ?

2023-03-04 00:40 UTC, akaszynski commented
> Should we add a cell_array method to match vtkCellArray and then deprecate cells

Yes. Mistakes were made years ago when naming it. I'm fine with doing it this release. It's a pretty big change, and we should give people a few releases to fix it.

2023-03-04 00:41 UTC, akaszynski submitted a review, later dismissed
Thanks for fixing this.

By the end of the year we can deprecate the old `cells` and use `cell` instead. Let's slowly transition to the new API over this year.

2023-03-04 06:24 UTC, tkoyama010 requested changes

2023-03-04 06:24 UTC, tkoyama010 commented on pyvista/core/dataset.py
> +        For a Tetrahedoren, get the point ids of the last face
```suggestion
        For a Tetrahedron, get the point ids of the last face

```

2023-03-04 14:24 UTC, tkoyama010 approved these changes
LGTM. Thanks.

2023-03-07 05:40 UTC, merged