Change source links to github
pyvista/pyvista pull request #4113
Opened 2023-03-09 20:33 UTC by akaszynski

The ``mne`` libray uses `sphinx.ext.linkcode` rather than ``sphinx.ext.viewcode`` and they link directly to github:
[mne.io.read_raw](https://mne.tools/stable/generated/mne.io.read_raw.html)

This PR implements the same logic and uses a source link to GitHub. It's much cleaner than having source within our documentation, and it has the (minor) added advantage of decreasing the build time and size of our docs.

2023-03-09 20:44 UTC, akaszynski commented
@jorgepiloto and @Revathyvenugopal162, you may consider making the changes implemented here into a general purpose sphinx extension as I think it's quite useful to link to github.

2023-03-09 20:56 UTC, akaszynski commented
@MatthewFlamm, seems that https://github.com/pyvista/pyvista/pull/4111 indeed fixed codecov.

2023-03-10 11:34 UTC, tkoyama010 requested changes

2023-03-10 11:34 UTC, tkoyama010 commented on pyvista/utilities/docs.py
> +        return None
```suggestion
    if not fn:  # pragma: no cover
        try:
            fn = inspect.getsourcefile(sys.modules[obj.__module__])
        except Exception:
            return None
        return None
```

2023-03-10 18:10 UTC, tkoyama010 approved these changes
LGTM

2023-03-10 23:13 UTC, merged