Change development status to stable
pyvista/pyvista pull request #4228
Opened 2023-04-03 23:43 UTC by akaszynski

Resolve #3975 by changing our "Development Status" to "Production/Stable".

Knowing how PyVista is being used ([~1.6k connections](https://github.com/pyvista/pyvista/network/dependents)!), I'm happy to take this a little closer to a v1.0 release.

Considering there are likely more changes to be made with the API (and it will probably never stop), I'm fine with delaying it past the end of this year. However, I also think we have enough API coverage as-is to call what we have as a 1.0.

It's for everyone to decide when, but I'm happy either way and regardless, I think we're "stable enough." right now.

2023-04-04 04:19 UTC, tkoyama010 approved these changes
I am sad that the fun times before the 1.0 release are over, but I have to admit that the API is more stable. I agree with this change.
Are there any criteria that other projects use when deciding to make the OSS version 1.0? I would like to know if anyone knows.

2023-04-04 06:41 UTC, adeak commented
> I also think we have enough API coverage as-is to call what we have as a 1.0.

I think in terms of API we have too much in places. Before we go 1.0 we should very seriously consider the major changes we still want to do and which will be harder after 1.0. Off the top of my head I can name https://github.com/pyvista/pyvista/pull/3764 (which drowned in "meh" and I ran out of time while I was still invested; woukd have to restart from scratch) and https://github.com/pyvista/pyvista/issues/4158. I'm sure there are other such examples if we dig into issues (e.g. https://github.com/pyvista/pyvista/issues?q=is%3Aissue+is%3Aopen+deprecate).

2023-04-04 07:06 UTC, tkoyama010 requested changes
Due to my whims, I had completely forgotten about these discussions lol . I guess anything that breaks backward compatibility like #1579 needs to be carefully considered. In any case, @akaszynski  has said he will release 1.0.0 over the next year, so it would be good to focus the discussion there before that. Why not label it something like `discuss-for-stable` and not release 1.0.0 until it's all closed?

2023-04-04 22:20 UTC, adeak commented
To be clear I don't object to the change _per se_. Just want to make sure that we (you) have weighed the trade-offs involved with the version bump. We've told ourselves often enough that breaking things is fine as we're <1.0 :) If the bottom line is that bumping the version is better then it's all good with me.

2023-04-05 10:31 UTC, adeak commented
Oh, and one last thought: I don't think the PyPI dev status and the version go strictly hand in hand. Pandas 0.24 was "Production/Stable" mid 2019. I think bumping the status is fine, my remarks are aimed at version 1.0 specifically.

2023-04-05 10:31 UTC, adeak approved these changes

2023-04-05 16:48 UTC, akaszynski commented
> As for the V1.0 discussions, let's save that for another day as we're not quite there yet -- still LOTS to do before I'd feel comfortable with a v1.0 release

Let's then keep the v1.0 discussion open in issues and merge this. Awaiting approval from @tkoyama010.

2023-04-05 21:42 UTC, tkoyama010 approved these changes

2023-04-06 21:57 UTC, merged