move vtk cell type to pyvista.cell type
pyvista/pyvista pull request #4485
Opened 2023-06-01 22:35 UTC by beroda

Resolves https://github.com/pyvista/pyvista/issues/4440

2023-06-01 22:52 UTC, tkoyama010 requested changes
Thanks working for this!

2023-06-01 22:52 UTC, tkoyama010 commented on tests/check_doctest_names.py
>      >>> import vtk
We can remove vtk import.
```suggestion
```

2023-06-01 22:55 UTC, beroda commented
@tkoyama010 Glad to help a little

2023-06-01 22:58 UTC, tkoyama010 approved these changes

2023-06-01 23:52 UTC, tkoyama010 commented
Please hold off merging until we merge #4486 and resolve the conflict with it.

2023-06-07 20:35 UTC, tkoyama010 approved these changes

2023-06-08 14:23 UTC, banesullivan approved these changes

2023-06-08 14:23 UTC, merged