Fix MultipleLines example
pyvista/pyvista pull request #4651
Opened 2023-07-12 22:09 UTC by AndCotOli

### Overview

Fixes  #4388 by using the plotter to rotate the camera.

### Details
Rotates the camera by 45 degrees and zooms out to see both lines.

2023-07-13 14:53 UTC, tkoyama010 commented
@AndCotOli
Thank you for your first contribution! Could you help us by following the steps in this section to make style corrections?
https://docs.pyvista.org/version/dev/extras/developer_notes.html#style-checking

2023-07-13 16:24 UTC, banesullivan commented
We could also use the pre-commit bot to fix the PR automatically

2023-07-14 09:07 UTC, tkoyama010 requested changes

2023-07-14 09:07 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_objects.py
> +    >>> actor = plotter.add_mesh(mesh)
```suggestion
    >>> actor = plotter.add_mesh(mesh, color='k', line_width=10)
```
I added options to match the appearance of the mesh with that before the change. Can you confirm that this is not a problem and approve the change?

2023-07-14 19:22 UTC, tkoyama010 approved these changes
LGTM. Great PR!

2023-07-15 12:50 UTC, merged