fix bug when add_mesh receives ndarray as texture
pyvista/pyvista pull request #4697
Opened 2023-07-22 10:21 UTC by yifanlu0227

### Overview

When Plotter.add_mesh(texture=...,) receives a np.ndarray as texture, it throws errors.

### Details

```
  File "/home/yfl/anaconda3/envs/hdr/lib/python3.9/site-packages/pyvista/plotting/plotter.py", line 3444, in add_mesh
    if texture:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

np.ndarray cannot be directly placed in the if-statement.

**Solution:**

I modify the line 3444 in `plotting/plotter.py` from 
```
if texture:
    if isinstance(texture, np.ndarray):
        texture = numpy_to_texture(texture)
    if not isinstance(texture, (_vtk.vtkTexture, _vtk.vtkOpenGLTexture)):
        raise TypeError(f'Invalid texture type ({type(texture)})')
    ...
```
to 
```
if texture is not None:
    if isinstance(texture, np.ndarray):
        texture = numpy_to_texture(texture)
    if not isinstance(texture, (_vtk.vtkTexture, _vtk.vtkOpenGLTexture)):
        raise TypeError(f'Invalid texture type ({type(texture)})')
    ...
```

2023-07-22 13:15 UTC, tkoyama010 commented
@yifanlu0227 Thanks for fixing this. Would you mind adding a test for this error?

2023-07-22 13:18 UTC, tkoyama010 requested changes
Would you mind adding a test for this error?

2023-07-22 13:43 UTC, yifanlu0227 commented
**Before fixing**: can not use np.ndarray as texture
![before](https://github.com/pyvista/pyvista/assets/45688237/d3c4ee26-7df3-49f0-8139-4fd392bc6cc1)

**After fixing**: 
![after](https://github.com/pyvista/pyvista/assets/45688237/1a72311f-25c5-4221-824f-73a19c7f15ea)

**Pyvista API Reference**: https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Plotter.add_mesh.html
![your_docs](https://github.com/pyvista/pyvista/assets/45688237/917b3368-b155-40d4-91f1-fac5cc82d951)


Source code are here:
[test_texture_ndarray.zip](https://github.com/pyvista/pyvista/files/12136589/test_texture_ndarray.zip)

2023-07-22 13:58 UTC, MatthewFlamm commented
I think the ask is to put a test into `tests/plotting/test_plotting`.  But this is a nontrivial ask since it might require adding in an image regression image.

I tested the truthiness of an ndarray with error, so this is the right fix.  If you are able to add a test it would be great, but IMO it is not required as you aren't touching the functionality.

```py
import numpy as np
a = np.asarray([1.0, 2.0])
if a:  # throws error
    pass
```

2023-07-22 14:10 UTC, yifanlu0227 commented
I got it, and thanks for your comment.@MatthewFlamm

2023-07-22 14:32 UTC, MatthewFlamm submitted a review, later dismissed

2023-07-22 18:37 UTC, adeak commented
> If you are able to add a test it would be great, but IMO it is not required as you aren't touching the functionality.

I disagree: there was an

2023-07-22 19:45 UTC, MatthewFlamm commented
Fair enough, if @yifanlu0227 is able to add a test in `tests/plotting/test_plotting.py`, it would be useful.  If you need help or feel this is too difficult, let us know.

2023-07-22 20:06 UTC, adeak commented
@yifanlu0227 there's a similar regression test [here](https://github.com/pyvista/pyvista/blob/3bc65eb63de53a17fc2df19ddbdba31db2042dcb/tests/plotting/test_plotting.py#L2133-L2142). Just create a plotter and try to add an ndarray texture just like in your examples here. Don't call `plt.show()` and then the image regression remarks from earlier don't apply :) We have a few tips about testing [here](https://docs.pyvista.org/version/stable/extras/developer_notes.html#testing) (and a bit later under "Unit Testing"). You can run the test in this module alone with `python -m pytest -v tests/plotting/test_plotting.py`, and even pick out a specific test by name with e.g. `python -m pytest -v tests/plotting/test_plotting.py -k test_interactive_update`.

But as @MatthewFlamm said: do let us know if you need help, or even if it seems too much and you'd prefer someone else to do it for you :)

2023-07-23 04:03 UTC, yifanlu0227 commented
I insert the test code in tests/plotting/test_plotting.py at about line 1242. The code are:

```
def test_plot_numpy_texture():
    """Text adding a np.ndarray texture to a plot"""
    globe = examples.load_globe()
    texture_np = np.asarray(imageio.imread(examples.mapfile))
    plotter = pyvista.Plotter()
    plotter.add_mesh(globe, texture=texture_np)

```

And I passed the test, was it OK? Please let me know any other thing I need to do :)

![2023-07-23 12-01-46](https://github.com/pyvista/pyvista/assets/45688237/2383a11f-c785-475e-99fb-2d5e561641a4)

2023-07-23 04:14 UTC, tkoyama010 commented
@yifanlu0227 Perfect! Let's add it.

2023-07-23 04:19 UTC, yifanlu0227 commented
@tkoyama010 done!

2023-07-23 04:28 UTC, tkoyama010 requested changes

2023-07-23 04:28 UTC, tkoyama010 commented on tests/plotting/test_plotting.py
> +def test_plot_numpy_texture():
This mark means skipping the test when the environment doesn't have `imageio`.
If the addition is OK, please Apply.
```suggestion
@pytest.mark.skipif(not HAS_IMAGEIO, reason="Requires imageio")
def test_plot_numpy_texture():
```

2023-07-23 04:36 UTC, tkoyama010 approved these changes
LGTM. Thanks for your first time contribution!

2023-07-23 04:37 UTC, tkoyama010 commented
If there are no other comments, this PullRequest will be merged after 24 hours.

2023-07-23 13:25 UTC, MatthewFlamm approved these changes
Coverage increased by 1 line.  LGTM.

2023-07-24 01:59 UTC, merged

2023-07-25 07:29 UTC, yifanlu0227 commented
Sorry to bother you, but I wonder if my pr will let me appear in contributor page? It's been 24 hours after the merge, but I haven't seen my name in contributor page. It would be my pleasure to be shown on it.

2023-07-25 08:47 UTC, adeak commented
@yifanlu0227 github knows you're a contributor :)
![screenshot with "contributor" highlighted](https://github.com/pyvista/pyvista/assets/17914410/0c7a99e7-50f9-492e-a9cd-40cb4f7c5f71)

It takes a lot of work to extract per-commit contributor info for the contributor graph so I expect the data is cached for a few days, and you'll show up soon :)

2023-07-25 09:00 UTC, adeak commented
Ah, no. It seems github only shows 100 contributors [here](https://github.com/pyvista/pyvista/graphs/contributors) 😞 I'm sorry. The good news is that if you contribute a second PR, you'll make the default list based on commit count :)

2023-07-25 09:12 UTC, tkoyama010 commented
Ah, I see. I didn't think it would be that hard to get on our contributor list 😆.

2023-07-25 09:21 UTC, tkoyama010 commented
@yifanlu0227 If you are looking for a place to contribute, we recommend adding an Examples section to docstrings that do not have one.

2023-07-25 11:31 UTC, MatthewFlamm commented
#1629 has a list of plotter examples that are missing, but this is older and I'm not sure if it was kept up to date.

2023-07-25 12:04 UTC, tkoyama010 commented
The list is up-to-date as there was a sprint during this period :)

2023-07-25 13:07 UTC, yifanlu0227 commented
I got it! I am deeply grateful for the help from all of you :)