Add use `TextActor3D` warning when scaling
pyvista/pyvista pull request #4775
Opened 2023-08-15 15:55 UTC by tkoyama010

### Overview

resolves #4768 and https://github.com/pyvista/pyvista/discussions/4721

### Details

- None

2023-08-18 15:06 UTC, akaszynski commented
Played around with this for a bit. Turns out the trick here is to just use CubeAxesActor2D as suggested in https://github.com/pyvista/pyvista/issues/699

```py
import vtk
import pyvista as pv

p = pv.Plotter()
p.add_mesh(pv.Sphere())
p.set_scale(1,1,2)
p.background_color = 'k'

axes = vtk.vtkCubeAxesActor2D()
axes.SetBounds(p.renderer.bounds)
axes.SetCamera(p.camera)
axes.SetFlyModeToClosestTriad()
axes.SetWidth(100)
p.add_actor(axes)

p.show()
```

![tmp](https://github.com/pyvista/pyvista/assets/11981631/feaf6e19-854c-4d6c-88dd-c4ec761af991)

Recommend we overhaul our cube axes actor instead. The 3d axes actor suffers from several issues and we could resolve this by simply switching over to vtkCubeAxesActor2D. I'll generate a PR for this.

2023-08-18 15:06 UTC, akaszynski requested changes
Recommending using vtkCubeAxesActor2D... hold off for a PR.

2023-08-19 07:49 UTC, tkoyama010 commented
I agree with using `CubeAxesActor2D`. However, some methods such as `SetXAxisMinorTickVisibility` are not present, so we need to think carefully about how to migrate to `CubeAxesActor2D`.

2023-08-19 18:34 UTC, akaszynski commented
> I agree with using `CubeAxesActor2D`. However, some methods such as `SetXAxisMinorTickVisibility` are not present, so we need to think carefully about how to migrate to `CubeAxesActor2D`.

Agreed. I think we should give the user the option of using either one. The "use_2d" might be just that option.

2026-09-06 07:11 UTC, closed without merging