Update/fix `connectivity` docs
pyvista/pyvista pull request #4872
Opened 2023-09-11 21:07 UTC by user27182

### Overview
Follow up from #4824.

### Details

- Fix `compute-volume` example to use the correct `connectivity` `scalar_range` (percentages taken from `threshold_percent` were previously incorrectly used)
- Fix list formatting for `versionadded` directive and `variable_input` param (lists were previously formatted as a paragraph)
- Add bold `**` formatting to highlight different example headings/sections
- Remove single float use case for `scalar_range` (must be a sequence with two values)
- Update `See Also` section with relevant methods (methods are now also hyperlinked)
- Other minor fixes to improve readability / clarity

2023-09-11 21:31 UTC, tkoyama010 requested changes
Thank you for suggesting the correction, I do have one suggestion. The docstring Example section of connectivity seems a bit long in my mind. Could you move that content to `examples/01-filter/connectivity.py`? For us, the docstring is an introduction to using the method by default in a simple way, and we would like to see a separate example page for more detailed usage.

2023-09-14 03:16 UTC, user27182 commented
> Could you move that content to `examples/01-filter/connectivity.py`?

Ok. I agree this is a better place for these. The examples have been moved with some edits / changes, and new, simpler, docstring examples added. See the updated PR Overview for details.

2023-09-14 05:44 UTC, tkoyama010 commented on examples/01-filter/connectivity.py
> +# Format scalar bar text for integer values.
```suggestion
# Plot the labeled regions.

# Format scalar bar text for integer values.
```

2023-09-14 05:44 UTC, tkoyama010 commented on examples/01-filter/connectivity.py
> +# Define scalar range of region to extract
```suggestion
# Define a scalar range of the region to extract
```

2023-09-14 05:44 UTC, tkoyama010 commented on tests/core/test_polydata.py
> +import pyvista
```suggestion
```

2023-09-14 05:44 UTC, tkoyama010 commented on tests/core/test_polydata.py
> +    mesh = pyvista.PolyData()
```suggestion
    mesh = pv.PolyData()
```

2023-09-14 05:44 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +        Extract a region using a cell id ``100`` as a seed.
```suggestion
        Extract a region using a cell ID ``100`` as a seed.
```

2023-09-14 05:44 UTC, tkoyama010 commented on pyvista/core/filters/poly_data.py
> +        filter.
```suggestion
        See :ref:`_connectivity_example` for more examples using this
        filter.
```

2023-09-14 05:45 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2023-09-14 06:44 UTC, tkoyama010 approved these changes

2023-09-15 00:16 UTC, merged