Add `principal_axes` feature
pyvista/pyvista pull request #4947
Opened 2023-09-21 22:19 UTC by user27182

### Overview

This PR adds a new function `pv.principal_axes_vectors()` to compute the principal axes (aka principal components) of a set of points.

By extension:
- the attribute `pv.DataSet.principal_axes` is added
- the convenience function `pv.principal_axes_transform()` is added
- `pv.fit_plane_to_points()` is updated accordingly so that it calls `pv.principal_axes_vectors()` internally

This PR also resolves #4705 and exposes the `i_resolution` and `j_resolution` params from `pv.Plane()` to `pv.fit_plane_to_points()`.

This PR also resolves #4711.

I am still not sure about some of the convenience functions:
- Should `pv.principal_axes_vectors()` be renamed? E.g. to `pv.principal_axes()` 
- Should the attribute `pv.DataSet.principal_axes_transform` also be added?
- Should `pv.DataSet.principal_axes` be removed (e.g. to limit the proliferation)
- Should `utilities.points.principal_axes_transform()` be moved elsewhere, e.g. to `transformations.py`?

Any other input or feedback on these methods to improve their utility is welcome.

### Details
This PR started off as adding a _new_ method to `pv.fit_plane_to_points()` as in #4705 to use covariance (from PCA) instead of SVD. The thought was that these were actually different methods. However, after implementing this "new" method, the tests revealed that the best-fit plane for the "different" methods was actually the same plane. The key finding is that:
``` python
# SVD
 _, _, axes_vectors = np.linalg.svd(data)  # row vectors, descending order
```
is mathematically the same as:
``` python
# PCA
covariance = np.cov(data, rowvar=False) 
 _, axes_vectors = np.linalg.eigh(covariance)  # column vectors, ascending order 
axes_vectors = axes_vectors.T[::-1]  # row vectors, descending order
```
By the same, I mean that these are equivalent up to a difference in axis sign, difference in axes values due to non-uniqueness of  the vectors, and up to a difference in numerical error. PCA is indeed a special case of SVD, and SVD is preferred for precision/numerical stability since it does not require computing the covariance matrix. 

This [article](https://arxiv.org/pdf/1404.1100.pdf) gives a good technical description of these methods and their relation, and in Section C remarks that "the columns of *V* [from SVD] are the principal components of *X*". Indeed, [`sklearn.decomposition.PCA`](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) states that it uses SVD to compute the principal components, further demonstrating that these methods are equivalent for this application.

As such, `pv.fit_plane_to_points()` now continues to only have and make use of the single method.

2023-09-21 22:28 UTC, user27182 commented
For some context, here's a sample output from the `pv.principal_axes_transform()` docstring. The transform is used to align the mesh to the XYZ axes.
![image](https://github.com/pyvista/pyvista/assets/89109579/2f7482aa-1981-4cd2-aea2-55f005bff2e5)

2023-09-21 23:35 UTC, tkoyama010 requested changes
Awesome job! I have reviewed it at this time. Please contact us again when ready.

2023-09-21 23:35 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +    and is automatically sized to fit the extents of the points.
```suggestion
    and is automatically sized to fit the extent of the points.
```

2023-09-21 23:35 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +    import numpy.random    >>> import pyvista
```suggestion
    >>> import numpy.random
    >>> import pyvista
```

2023-09-21 23:35 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +    >>> np.random.seed(42)
Great. We can fix the output figure by this.

2023-09-21 23:35 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +    --------
This section is informative enough to add a stand-alone example script. It would be better to add a script.

2023-09-22 07:33 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +    --------
Same with https://github.com/pyvista/pyvista/pull/4947#discussion_r1333697020_ .

2023-09-22 21:52 UTC, user27182 commented
Thanks for reviewing and for the docstring fixes. I will rework the examples. 

I have also found that the API should be reworked because it's sometimes helpful to have both the axes _and_ the transformation returned by `principal_axes_vectors` instead of just one or the other. Also, the inverse transform is helpful to return as well because often the workflow is: transform- > do stuff -> transform back. I will push these changes soon.

2023-09-23 05:10 UTC, user27182 commented
@tkoyama010 I have added the inverse transform and updated the API (among other changes). I believe this should be the last big change to the code and API. I have not yet reworked the examples, however. Feel free to review current changes if you'd like or wait until the examples are changes.

2023-09-23 05:55 UTC, tkoyama010 commented on pyvista/core/utilities/points.py
> +                    raise ValueError("Direction vectors must be distinct.")
```suggestion
    for i, vec1 in enumerate(directions):
        for j, vec2 in enumerate(directions[i + 1 : :]):
            if vec1 is not None and vec2 is not None and np.allclose(vec1, vec2):
                raise ValueError("Direction vectors must be distinct.")
```

2023-09-26 04:42 UTC, user27182 commented
@tkoyama010 I'm not quite sure how the integration tests work. Tests with GeoVista are failing, I'm sure why, but perhaps a numpy upgrade can resolve this? see [stackoverflow link](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp). Is it possible to alter the test config like that?

2023-09-26 05:06 UTC, tkoyama010 commented
I re-run GitHubActions. Let's see if the error reproduces each time.

2023-09-26 05:08 UTC, tkoyama010 commented
Ummm. Looks like it will reproduce. @bjlittle Do you have any idea about this?

2023-09-26 05:10 UTC, tkoyama010 commented
> Edit: geovista [requires numpy>=1.21](https://github.com/bjlittle/geovista/blob/8a9b6429c4ab3480496ac8986f94562033be94b7/requirements/geovista.yml#L16C17-L16C17).
> Some [users reported](https://stackoverflow.com/a/68775561) fixing this issue with numpy ==1.21.1. Is it possible to run the CI test with this version of numpy?

Sure.

2023-09-26 05:55 UTC, user27182 commented
I did make changes to transform-related code in the recent commits and I see that the GeoVista test fails with  `geovista.bridge import Transform`, so it may be the changes I made which are the cause. I will investigate further tomorrow.

2023-09-26 09:04 UTC, bjlittle commented
@tkoyama010 and @user27182 

Interesting 🤔

I've not seen this before, I'll spin up and investigate too 👍

2023-09-26 09:07 UTC, bjlittle commented
[numpy 1.26.0](https://github.com/numpy/numpy/releases/tag/v1.26.0) was just release on 16 Sep 2023 ... perhaps this is related ...

2023-09-26 10:54 UTC, bjlittle commented
See #4957

2023-09-26 16:06 UTC, user27182 reviewed
Is it possible to modify the pre-commit so that it catches this docstring error before the build fails?

i.e. complain when there is a missing indent following a directive, e.g.:
```
.. directive::
Some text
```
which should be formated as:
```
.. directive::
    Some text
```

2023-09-26 22:32 UTC, tkoyama010 commented
> Is it possible to modify the pre-commit so that it catches this docstring error before the build fails?

Good point. I looked at `matplotlib` `pre-commit` settings and they seem to be using `check-docstring-first`. I don't know if this will meet your requirements, but we'll give it a try with #4959.

2023-09-27 16:13 UTC, user27182 commented
> I looked at `matplotlib` `pre-commit` settings and they seem to be using `check-docstring-first`. I don't know if this will meet your requirements, but we'll give it a try with #4959.

Thanks for looking into this. Unfortunately #4959 did not resolve the issue. It is easy to check if this is caught by the pre-commit by simply adding/removing indentation for a directive's text block.

I have opened a new issue with numpydoc https://github.com/numpy/numpydoc/issues/507

2024-08-17 05:36 UTC, user27182 commented
Most of this PR has been implemented via 
- #6346 
- #6354 
- #6485 

Some items which may be useful but not yet implemented:
- Function pv.random_sample_points() for sampling points
- Fix for https://github.com/pyvista/pyvista/issues/4711
- New standalone example

2025-01-22 15:35 UTC, closed without merging