Added function "spherical_to_cartesian(r, theta, phi)" to features.py
pyvista/pyvista pull request #5003
Opened 2023-10-02 02:23 UTC by denizkirbiyik

Added a function that converts spherical coordinates to 3D cartesian coordinates using the following formulas:
x = r*sin(theta)*cos(phi)
y = r*sin(theta)*sin(phi)
z = r*cos(theta)

resolves #4979

2023-10-02 02:29 UTC, tkoyama010 commented
pre-commit.ci autofix

2023-10-02 02:32 UTC, tkoyama010 commented
@denizkirbiyik 
Thank you for the PR. This is a very nice addition. We need to add testing to this. Mention me if you need help.

2023-10-03 17:09 UTC, MatthewFlamm commented on pyvista/core/utilities/features.py
> +        Angle (radians) with respect to the polar axis. Also known
vtk defines theta and phi the other way around.  I think we should align to how vtk operates.

See https://vtk.org/doc/nightly/html/classvtkSphericalTransform.html#details

#4965 and `pyvista.Sphere` are already consistent with this vtk operation.

2023-10-04 02:20 UTC, tkoyama010 commented on pyvista/core/utilities/features.py
> +    x, y, z : numpy.ndarray
```suggestion
    numpy.ndarray, numpy.ndarray, numpy.ndarray
```

2023-10-04 04:21 UTC, tkoyama010 commented
pre-commit.ci autofix

2023-10-04 04:28 UTC, tkoyama010 commented on tests/core/test_utilities.py
> +    x, y, z = pv.spherical_to_cartesian(r, theta, phi)
```suggestion
    x, y, z = pv.spherical_to_cartesian(r, phi, theta)
```

2023-10-04 04:28 UTC, tkoyama010 commented on tests/core/test_utilities.py
> +    assert np.allclose(pv.spherical_to_cartesian(r, theta, phi), points)
```suggestion
    assert np.allclose(pv.spherical_to_cartesian(r, phi, theta), points)
```

2023-10-04 04:29 UTC, tkoyama010 commented on tests/core/test_utilities.py
> +    r, theta, phi = points.T
```suggestion
    r, phi, theta = points.T
```

2023-10-04 04:36 UTC, tkoyama010 submitted a review, later dismissed
LGTM. Thanks for your contribution!

2023-10-04 04:42 UTC, tkoyama010 approved these changes

2023-10-04 05:09 UTC, tkoyama010 requested changes
~~Because the backward compatibility of `cartesian_to_spherical` needs to be addressed, block the merge until the review is complete.~~ _Edit: I'm sorry. I was mistaken._

2023-10-04 06:50 UTC, tkoyama010 approved these changes

2023-10-04 10:48 UTC, tkoyama010 requested changes
Please wait until #5014 is merged to organize PRs.

2023-10-04 12:13 UTC, tkoyama010 approved these changes

2023-10-04 14:33 UTC, merged