Add off screen devcontainer option
pyvista/pyvista pull request #5128
Opened 2023-10-25 16:33 UTC by MatthewFlamm

### Overview

Closes #5125.  This PR adds in a second devcontainer option to do off screen rendering.  This is needed in case users cannot connect via vnc for some reason, or they want to test osmesa vtk flavor etc.

### Details
We could also consider other flavors with other vtk variants, but I'm less familiar.

TODO:

- [ ] add documentation about the options including the live viewer for the default devcontainer.

2023-10-25 17:19 UTC, MatthewFlamm commented
To test the offscreen container you can click "\<code\>" button -> "..." -> "New with options..." -> change "Dev container configuration" to "Osmesa".  The default is currently "desktop-lite".  It is working for me currently both ways.

offscreen tested with 
```py
import pyvista as pv
pv.Sphere().plot()
pv.Sphere().plot(screenshot="test.png")
```
![image](https://github.com/pyvista/pyvista/assets/39341281/f4ebe488-3fd5-43f7-a784-8de8558d1c4b)

2023-10-25 18:11 UTC, MatthewFlamm commented
I have added a section to the CONTRIBUTING.rst on this.  Not sure if it should also go somewhere else in addition...  

I have also removed the documentation on the GitPod container as I'm no longer using it, and am using codespaces primarily.  If we don't have a champion to keep it current, we should not recommend it to users.  We could consider deleting it, but I don't see harm in keeping it in case some users prefer this (and then they can help us maintain it).

2023-10-25 23:37 UTC, tkoyama010 commented
Awesome. Thanks for sharing your knowledge!

2023-10-26 23:38 UTC, tkoyama010 requested changes

2023-10-26 23:38 UTC, tkoyama010 commented on CONTRIBUTING.rst
> +`here <https://github.com/devcontainers/features/tree/main/src/desktop-lite#connecting-to-the-desktop>`_
A UI design expert commented that it is helpful for readers to explicitly indicate the title of the link when add a link ([Jimenez Gacha & Presedo-Floyd - Accessibility best practices for authoring Jupyter notebooks](https://youtu.be/onjRLjveGxk?si=CkG_sZ_sSTIwB36X)). I didn't know that either, so I will try to do it from now on.
```suggestion
`Connecting to the desktop <https://github.com/devcontainers/features/tree/main/src/desktop-lite#connecting-to-the-desktop>`_
```

2023-10-27 10:09 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2023-10-28 01:38 UTC, banesullivan approved these changes
Thanks, @MatthewFlamm!

2023-10-28 01:44 UTC, tkoyama010 approved these changes

2023-10-28 05:13 UTC, merged