feat: Add option to always get screenshots from plotter shows
pyvista/pyvista pull request #5197
Opened 2023-11-15 10:56 UTC by AlejandroFernandezLuces

### Overview

This PR adds an option to always produce screenshots instead of showing the plotter when performing a `pl.show()`. We need this feature in some PyAnsys projects, where we need to have the screenshots of several plotters without modifying the underlaying code.

Let me know your thoughts about this feature 🙂 

### Details

I'm using UUID library to generate unique identifiers for the screenshot filenames. This may be substituted by some attribute from PyVista, but not sure if any would ensure that the name is unique.

2023-11-15 18:27 UTC, tkoyama010 requested changes

2023-11-15 18:27 UTC, tkoyama010 commented on pyvista/plotting/plotter.py
> +        if self.notebook or pyvista.SCREENSHOTS_ONLY:
This is a great feature. Thank you. I will follow the `OFF_SCREEN` naming convention and suggest the variable name `ON_SCREENSHOT`.
```suggestion
        if self.notebook or pyvista.ON_SCREENSHOT:
```

2023-11-16 22:00 UTC, tkoyama010 submitted a review, later dismissed
LGTM

2023-11-17 12:32 UTC, AlejandroFernandezLuces commented
Changed to pytest `tmpfolder` for image cleanup. Also, added a fixture that resets the global variables to the values it had before running the tests, I think it's cleaner and can be reused in other tests.

2023-11-17 12:35 UTC, MatthewFlamm approved these changes
I can foresee users also wanting sequentially numbered filenames to keep track of which image is which, but a future PR to add in a configurable mode.

2023-11-17 14:07 UTC, tkoyama010 approved these changes

2023-11-18 06:26 UTC, merged