[PATCH] Fix plane geometry orientation for `direction=(0,1,0)` case
pyvista/pyvista pull request #5435
Opened 2024-01-04 22:16 UTC by user27182

Fix #5405.

This is an alternative proposed solution to #5406 and is specific to `Plane` only.

2024-01-06 11:27 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_objects.py
> +    # for special cases to maintain compatibility with older versions, see GH#5405
```suggestion
    # https://github.com/pyvista/pyvista/pull/5435
```

2024-01-06 11:27 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +    # with older versions of pyvista
```suggestion
    # https://github.com/pyvista/pyvista/pull/5435
```

2024-01-06 11:27 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +    # short axis should be parallel to x-axis
```suggestion
```

2024-01-06 11:27 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_objects.py
> +    # Rotate so the plane's normal points in the +x direction
```suggestion
```

2024-01-06 11:27 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_objects.py
> +
```suggestion
```

2024-01-06 11:28 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_objects.py
> +
```suggestion
```

2024-01-06 11:30 UTC, tkoyama010 approved these changes
Thank you for the clear explanation in the comment. I have moved the explanation to the docstring to make this clear to users.

2024-01-06 11:34 UTC, tkoyama010 commented
@bjlittle Could you confirm that this patch will resolve https://github.com/bjlittle/geovista/issues/447? If it resolves the issue, we will release a minor version immediately.

2024-01-06 12:55 UTC, bjlittle commented
Awesome effort guys! 🍻

I'll make time to test this evening and let you know asap, thanks 👍

2024-01-06 14:52 UTC, user27182 commented on pyvista/core/utilities/geometric_objects.py
> +
```suggestion
    .. warning::
    
        :func:`~pyvista.Plane` is known to have an incorrect orientation 
        when ``direction`` is exactly parallel to the y-axis, i.e. 
        ``direction=(0, 1, 0)`` or `direction=(0, -1, 0)``. This behavior is 
        maintained for compatibility with older versions, see 
        `pyvista/#5405 <https://github.com/pyvista/pyvista/issues/5405>`_.
    
        To obtain the correct orientation for these special cases, it's necessary
        to rotate the plane an additional 90 degrees along its normal axis after 
        instantiation, e.g.
    
        .. code-block:: python
        
            mesh = pv.Plane(direction=(0, 1, 0))
            mesh.rotate_y(90, inplace=True)
 
```

2024-01-06 15:07 UTC, user27182 commented
I'll note that I don't think the reason for this bug is that the orientation of `Plane` is under-determined. I gave my reasons here https://github.com/pyvista/pyvista/issues/5405#issuecomment-1878307637 for why I think it's possible to fully determine the expected output for this case, and why I believe that the orientation of plane is currently correct.

As such, this PR isn't fixing a bug with `Plane`, but rather is deliberately re-introducing a bug that was previously fixed (for compatibility reasons).

Long term, I think the true fix is to keep the current implementation for Plane (i.e. revert this PR in the future) and update downstream projects that rely on this behavior accordingly, e.g. implement the suggested changes such as this one https://github.com/bjlittle/geovista/issues/447#issuecomment-1879565162

2024-01-06 16:23 UTC, tkoyama010 submitted a review, later dismissed

2024-01-06 17:04 UTC, user27182 commented
pre-commit.ci autofix

2024-01-06 23:21 UTC, bjlittle commented
@user27182 @tkoyama010 

Okay, I can confirm that this patch fixes the issue in `geovista`. Amazing. Thanks so much 🍻 

Given the suggestion of @user27182 above, I'll try this change within `geovista` to see how it behaves and report back here ASAP.

I agree with @user27182, it would make more sense for `geovista` to change, rather than regress the behaviour in `pyvista`.

2024-01-06 23:24 UTC, tkoyama010 approved these changes

2024-01-06 23:55 UTC, tkoyama010 commented
Once @banesullivan approves this PR, we will do a patch release. He seems to be busy so please wait a bit.

2024-01-07 01:34 UTC, bjlittle commented
@user27182 @tkoyama010 

Okay, great news. You can close this PR!

We've found a really sweet compromise here.

I can confirm that we can fully contain the fix within `geovista`, so there is no need for `pyvista` to regress behaviour by applying this patch. I think merging this patch would compromise `pyvista` and just cause you guys headaches, as already mentioned by @user27182.

So, given that a plane is (unexpectedly) rotated when created with `direction=(0, 1, 0)`, thanks to @banesullivan for spotting this, I've decided to completely avoid this behaviour.

I realised that we can get the same end result in `geovista` by adopting the default `Plane(..., direction=(0, 0, 1))` and then applying a `rotate_x(90, inplace=True)` on the resultant plane instead. 

The idea of performing the additional rotation was suggested by @user27182, so thanks for that 🍻 

I can instead release a patch on `geovista` that includes a minimum pin of `pyvista>=0.43.1` ... I simply need to remove new deprecations warnings being generated by the latest version of `pyvista`, but otherwise I'm now unblocked.

Thanks guys for the awesome support. Totally first class 💯🥳🎖️

2024-01-07 09:42 UTC, bjlittle commented
Although, a warning being added to the `Plane` docstring is still of great value to the community and developers, as it documents the behaviour when using `direction=(0, 1, 0)`.

Perhaps this could be the focus of this pull-request now ?

2024-01-07 16:57 UTC, user27182 commented
I'm glad this could be resolved. I agree a warning should be added and possibly patched for both 0.42 and 0.43. The warning could be added inside of `translate`.

2024-01-10 02:56 UTC, banesullivan commented
+1 for adding a warning here! Great work everyone digging into this!

2024-01-11 05:30 UTC, user27182 commented
Do we want a warning in the docs or a warning in the code (e.g. in translate)? Or both?

Is the plan to patch 0.42, 0.43, or both ? (The behaviour changed in 0.42.2)

2024-01-11 05:55 UTC, tkoyama010 commented
> Do we want a warning in the docs or a warning in the code (e.g. in translate)? Or both?

Both please.

> Is the plan to patch 0.42, 0.43, or both ? (The behaviour changed in 0.42.2)

Yes. We will.

2024-01-12 06:08 UTC, tkoyama010 requested changes
Set Request changes to prevent merging before changing the above.

2024-01-12 07:40 UTC, user27182 commented
I encountered some (still) unexpected behaviour while adding a few edge cases to codify what I believed to be the current expected behaviour of `Plane`.

So, I'm working on adding tests to better understand the broader impact the patch from 0.42.2 had on the orientation for other geometric objects. I'm leaning towards adding regression tests for all objects which have a `direction` or `normal` parameter. If we include all parametric objects, there are approx. 33 objects with these parameters which may have been affected by the changes to `translate`. So, I think I'll generate 33 orientation test images based on the output from 0.42.1, and then compare the output from 0.43.1.

2024-01-13 05:39 UTC, user27182 commented
pre-commit.ci autofix

2024-01-13 08:31 UTC, user27182 commented
Not sure what we want the scope of this PR to be now? What do we want to patch, exactly? 

We could do something like what was originally proposed in #5406 and try to restore the 0.42.1 orientation behaviour for all objects.

At the same time, we could add a general warning to `translate` to inform users that `direction` is unstable and should be avoided, and that objects should instead be rotated manually using `rotate_x`, etc. ? (similar to the fix implemented in geovista).

Thoughts?

2024-01-13 20:36 UTC, banesullivan commented
Excellent investigative work here, @user27182! This problem is the worst case scenario in my mind when this started... 

>  try to restore the 0.42.1 orientation behaviour for all objects. .. At the same time, we could add a general warning to translate to inform users that direction is unstable and should be avoided ...

+1 for this from me. I think the safest thing to do here is restore previous behavior and issue warnings.

2024-01-15 17:19 UTC, user27182 commented
Looks like #4890 and/or #5004 may have also introduced changes to the orientation geometry for `Cylinder`.

Here is the v0.42.1 output:
![direction_objects object_function3](https://github.com/pyvista/pyvista/assets/89109579/b83af4fc-5f31-434e-9a96-a69f761f7601)
and v0.43.1 output:
![direction_objects object_function3](https://github.com/pyvista/pyvista/assets/89109579/2b0860ec-8063-49d9-b3d6-ca669fec3be6)

If we look at `direction=(1,0,0)`, for example, we see that the geometry has been rotated 180 degrees. Visually the cylinder appears to have the same general shape and orientation, but the point IDs / scalars differ between versions.

2024-01-15 22:28 UTC, user27182 commented
In [3181fab](https://github.com/pyvista/pyvista/pull/5435/files/4de6bda435f740ba47aaceb372809ed914269730..3181fabb6c5d54b369716ba914e81673bf550526), the new regression images (and minor changes to core tests) for all direction/orientation objects are all consistent with the output from `v0.42.1`.

Since #4674 is what first introduced this kind of axis-shifting behaviour (but without any regression tests), I was also concerned that the outputs from `v0.42.1` might also differ from `v0.41.1`. And so I have also double-checked that the images in In https://github.com/pyvista/pyvista/pull/5435/commits/3181fabb6c5d54b369716ba914e81673bf550526 are consistent with `v0.41.1`. And, much to my relief, they are indeed the same, except for `Sphere` and `Plane`, which had incorrect directions in `v0.41` and prior (this was fixed by #4674 in `v0.42`).

2024-01-15 22:40 UTC, user27182 commented
I believe the technical part of this patch is now finished: the object orientations are now consistent with `v0.42` and prior.

Note that this patch effectively re-introduces bug #4853 as a result. Do we want to include a 'fix' for this as part of this patch? Perhaps locally in `ParametricEllipsoid` with a rotation after calling `translate`? Though I'm not convinced this is easily fixed since I think the fundamental issue stems from `translate` being discontinuous and under-defined, and the bug is not specific to `ParametricEllipsoid`.

If anyone cares to review the changes, test things out locally, etc. feel free to do so now.

I believe adding warnings to code and/or docs is all that remains otherwise.

2024-01-15 23:00 UTC, user27182 commented
Also, the regression tests exposed a new bug: `CylinderStructured` seems to completely disappear from the plot with `direction=(0, 0, -1)`
![direction_objects object_function4-False](https://github.com/pyvista/pyvista/assets/89109579/b1350735-7f71-40ab-9e5d-3f3bf1e283bd)

I don't have time to investigate this any further at this point and will leave it for now. Otherwise, all the other images / objects look fine though.

2024-02-01 03:42 UTC, user27182 commented
@banesullivan @tkoyama010 Is there still a desire to get this patch merged? In terms of the technical changes and fixes listed in the top comment?

2024-02-03 03:04 UTC, tkoyama010 commented
Yes. Of course. Let's set this as "ready for review" and start reviewing.

2024-02-03 05:39 UTC, user27182 commented
Ok thanks. The technical changes are ready but the documentation and any warnings in code have not yet been updated. Please make suggestions for this as I'm not sure what kind of warnings or information we want to provide with respect to the instability of `translate` or how to avoid it.

2024-02-13 19:46 UTC, user27182 commented
"pre-commit.ci autofix"

2024-02-13 19:47 UTC, user27182 commented
pre-commit.ci autofix

2024-02-25 07:23 UTC, tkoyama010 commented
github-actions deploy

2024-02-25 07:24 UTC, tkoyama010 commented
github-actions preview

2024-06-03 20:43 UTC, user27182 commented
Closing since the initial motivation for this PR was to resolve downstream issues which were resolved early on, see https://github.com/pyvista/pyvista/pull/5435#issuecomment-1879907332.

Also, the tests from this PR have already been merged in #5614.

2024-06-03 20:43 UTC, closed without merging