Allow computing number of cell vertices in `compute_cell_sizes`
pyvista/pyvista pull request #5474
Opened 2024-01-16 20:26 UTC by MatthewFlamm

### Overview

Add option to include 'VertexCount' in the returned data.

### Details

This is needed for implementing https://github.com/MatthewFlamm/pyransame/issues/29.

I opted to default to `False` for backwards compatibility. It should also be a rare usage.

2024-01-16 20:27 UTC, MatthewFlamm commented on pyvista/core/filters/data_set.py
> +            Specify whether or not to computer the number of vertices
```suggestion
            Specify whether or not to compute the number of vertices
```

2024-01-16 20:27 UTC, MatthewFlamm commented on pyvista/core/filters/data_set.py
> +            in 0D cells.
```suggestion
            of 0D cells.
```

2024-01-17 03:17 UTC, tkoyama010 requested changes
Thanks for the change. I'm glad to see that `pyransame` development is going well. I have a suggestion about the parameter description.

2024-01-17 03:17 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +            of 0D cells.
I rewrite the docstring based on the [SetComputeVertexCount](https://vtk.org/doc/nightly/html/classvtkCellSizeFilter.html#af459249cf230a59304e86fbaf9503099) manual. If my understanding is correct, please approve.
```suggestion
            Specify whether or not to compute sizes for vertices and 0D cells.
            The computed value is the number of points in the cell.
```

2024-01-17 12:48 UTC, MatthewFlamm commented on pyvista/core/filters/data_set.py
> +            Specify whether or not to compute sizes for vertices and 0D cells.
```suggestion
            Specify whether or not to compute sizes for vertex and polyvertex cells.
```

2024-01-17 12:59 UTC, tkoyama010 approved these changes
LGTM

2024-01-18 12:25 UTC, merged