Add core typing to documentation
pyvista/pyvista pull request #5621
Opened 2024-02-14 20:55 UTC by user27182

### Overview

Add documentation for the type definitions in `core._typing_core`. 

Specifically:
1. make the `_typing_core` types in docstrings and annotations linkable.
    - Example issue: the docs for [set_array](https://docs.pyvista.org/version/0.43/api/core/_autosummary/pyvista.DataSetAttributes.set_array.html) have a `data : Array` parameter in the docstring, but it is not linkable. This makes it unclear what is meant by `Array`.
  
2. Make the `_typing_core` annotations in function signatures more readable.
    - Example issue: since aliases are automatically expanded by sphinx, the annotations for array-like types can take up to 8 lines for a single parameter. See screenshot in https://github.com/pyvista/pyvista/pull/5571#issuecomment-1939197128

The additions in this PR are similar to the configuration for [ColorLike](https://docs.pyvista.org/version/stable/api/utilities/_autosummary/pyvista.ColorLike.html), which is a pyvista type alias that is linkable and is defined formally the docs. (See the `color` param for [ChartBox](https://docs.pyvista.org/version/stable/api/plotting/charts/_autosummary/pyvista.chartbox#pyvista.ChartBox) as an example of its use in docstrings).

2024-02-14 21:43 UTC, tkoyama010 submitted a review, later dismissed
LGTM

2024-02-14 21:47 UTC, tkoyama010 approved these changes

2024-02-14 21:53 UTC, user27182 commented on pyvista/core/_typing_core/__init__.py
> +# CellArrayLike.__doc__
I wasn't sure how to document these. @darikg do you have a suggestion for these?

2024-02-14 22:00 UTC, user27182 commented
Thanks for the fixes and quick approval!

Might be good to do a manual check before this is merged. The aliases need `from __future__ import annotations` to be documented properly by sphinx. But this is only defined in `_alias`, whereas the `__doc__`s  are added in `__init__`.

So, I'm not sure if sphinx will actually pick up the docstrings correctly or not. I'm also curious to see how the `TypeVar` will appear in the docs.

2024-02-14 22:04 UTC, tkoyama010 requested changes
Thanks. I will check in my local. It would be nice if we could do a preview build, but that mechanism is being rebuilt in #5360.

2024-02-15 17:36 UTC, user27182 commented
I have not been able to review the docs locally. The docs are approx 3.5GB in size, and download speeds seem to be capped at 500KB/sec, which means downloading them takes approx 2 hours. For some reason, the download keeps failing for me part way through and I have to re-retry. The download has failed 4 times for me already, not sure if that's just my machine or my web browser.

2024-02-15 20:14 UTC, tkoyama010 commented
> I have not been able to review the docs locally. The docs are approx 3.5GB in size, and download speeds seem to be capped at 500KB/sec, which means downloading them takes approx 2 hours. For some reason, the download keeps failing for me part way through and I have to re-retry. The download has failed 4 times for me already, not sure if that's just my machine or my web browser.

The volume of documentation is bloated and is straining our development efficiency. This is a significant problem. We are discussing it in #5352 and would appreciate any ideas you may have.

2024-02-18 05:00 UTC, user27182 commented
I still can't download the docs locally for review 😔, not sure what the issue is or if there are any workarounds...

2024-02-18 06:38 UTC, tkoyama010 commented
github-actions preview

2024-02-18 09:44 UTC, tkoyama010 commented
github-actions preview

2024-02-18 11:20 UTC, tkoyama010 commented
> 🚀 Deployed on https://65d1e17a91a5a723b3ec9543--meek-duckanoo-d2f5ec.netlify.app

Preview is deployed. Let's review!

2024-02-19 06:45 UTC, tkoyama010 commented
github-actions preview

2024-02-19 22:31 UTC, user27182 commented
> 🚀 Deployed on https://65d306c928293de4dfcc21a8--meek-duckanoo-d2f5ec.netlify.app

aliases are still expanded and not linked (I am checking the docs for `pyvista.DataSetAttributes.set_array` specifically), and __doc__ strings aren't shown either. Maybe https://github.com/pyvista/pyvista/pull/5621/commits/bb86bf6553a9466cd573230250f0f0077421ba58 will fix it?

2024-02-19 23:52 UTC, tkoyama010 commented
github-actions preview

2024-02-20 01:37 UTC, user27182 commented
The docs still have the same issues: aliases are still expanded, and docstrings aren't showing.

The PR which added ColorLike (PR #2175) also added exclusions to `numpydoc_validation_exclude`... maybe that's the issue, and new exclusions need to be added ??

2024-02-20 04:23 UTC, tkoyama010 commented
github-actions preview

2024-02-20 04:25 UTC, tkoyama010 commented
Feel free to comment on the commands to see preview. Your account also has the authority I guess.

2024-02-20 08:58 UTC, user27182 commented
github-actions preview

2024-02-21 07:14 UTC, user27182 commented
github-actions preview

2024-02-21 16:24 UTC, user27182 commented
github-actions preview

2024-02-21 17:43 UTC, user27182 commented
github-actions preview

2024-02-21 20:08 UTC, user27182 commented
github-actions preview

2024-02-21 21:30 UTC, user27182 commented
Finally found the magic combination for the docs. Type alias docstrings are showing, and the `Array` object in `datasetattributes.set_array` now links directly to the Alias. 

LGTM

2024-02-23 04:30 UTC, user27182 commented
github-actions preview

2024-02-23 15:16 UTC, user27182 commented
> Deployed on https://65d830adf48efa981506a497--meek-duckanoo-d2f5ec.netlify.app

It looks like the links are no longer working with `datasetattributes`. I suspect this may be from 5dbc9bc, which removed the `from __future__ import annotations` statement. This could mean that it may be necessary to add that line to _every_ file where the alias is used.

2024-02-23 20:06 UTC, user27182 commented
github-actions preview

2024-02-23 22:12 UTC, user27182 commented
> 🚀 Deployed on https://65d9097e1d98156ae7d89bd8--meek-duckanoo-d2f5ec.netlify.app

The alias in the set_array function signature is now correctly set as `ArrayLike`. 

The alias in signature is not linked, however. This seems to be a bug, with a possible workaround here.
https://github.com/sphinx-doc/sphinx/issues/10785

2024-02-24 00:53 UTC, user27182 commented
github-actions preview

2024-02-24 02:28 UTC, user27182 commented
This PR looks good to me. 

I am a bit concerned that some references to `ArrayLike` might not get picked up correctly in the future for modules that will import `ArrayLike`. But, this issue likely applies to `ColorLike` as well. So,I think maybe a separate PR can work to resolve that if or when that happens.

2024-02-25 07:17 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2024-02-25 23:33 UTC, tkoyama010 commented
Please wait while we merge #5670 first.

2024-02-26 02:32 UTC, merged

2024-02-28 23:07 UTC, user27182 commented
> I am a bit concerned that some references to `ArrayLike` might not get picked up correctly in the future for modules that will import `ArrayLike`. But, this issue likely applies to `ColorLike` as well. So,I think maybe a separate PR can work to resolve that if or when that happens.

Unfortunately, this issue has surfaced. Looking at the docs published here before this PR was merged,
https://65d951a0b791cd8a5fda3017--meek-duckanoo-d2f5ec.netlify.app/api/core/_autosummary/pyvista.polydata

we see that PolyData's array-like aliases are expanded.

<img width="757" alt="image" src="https://github.com/pyvista/pyvista/assets/89109579/201311b6-c6de-4fff-b169-619dc9b4f91b">

2024-02-28 23:21 UTC, user27182 commented
I wonder if @dcbr can help.

This PR added `ArrayLike` aliases to the docs, similar to what was done for `ColorLike` in #2175.
But, we are having issues where it seems that `from __future__ import annotations` may need to be added to every file where we want the alias to display correctly in the docs. Ideally we wouldn't need to do this.

If we look at the docs for [ChartBox](https://docs.pyvista.org/version/stable/api/plotting/charts/_autosummary/pyvista.chartbox#pyvista.ChartBox), it has a working `ColorLike` alias in the parameters. And, looking at the source code, I see that `charts.py` does _not_ have a the `from future` import statement.

Do you know how this was achieved?
Not sure if there's a trick with how the alases are imported, or a config hack that was missed by this PR (but is part of #2175).

2024-02-29 09:41 UTC, dcbr commented
It's been a while since I messed with those aliases, I know it was a lot of trial and error and don't remember the exact "solution"; but I will try to have another look and see if I can help resolve it.

2024-02-29 16:30 UTC, user27182 commented
> It's been a while since I messed with those aliases, I know it was a lot of trial and error and don't remember the exact "solution"; but I will try to have another look and see if I can help resolve it.

Thanks, this PR tried to copy the same config, and there was also lots of trial and error. A possible source of the issue may be from:
1. differences in how the aliases are defined and imported into the `pyvista` namespace
    - `ColorLike` gets imported lazily (like many `plotting` objects`), whereas `ArrayLike` gets imported explicitly via `core._typing_core.__init__`
    - This may be relevant since `from __future__ import annotations` is definitely needed in the modules where the aliases are defined, so maybe the import messes with this somehow
2. the `plotting._typing` modules imports these explicitly while `TYPE_CHECKING`: https://github.com/pyvista/pyvista/blob/e338c17ba85b7bc2c9cd4903c9a3ebd855555c83/pyvista/plotting/_typing.py#L11-L13
    - These imported modules use `ColorLike`, so perhaps that's what allows the docs to recognize the aliases
    - The `ArrayLike` modules do not have this kind of import 


After writing this, I strongly suspect that # 2 is the issue, and that adding a conditional `TYPE_CHECKING` import for any/all modules which may use the `ArrayLike`  aliases may fix this.

2024-03-20 13:04 UTC, dcbr commented on doc/source/api/core/typing.rst
> +.. autodata:: ArrayLike
Sorry, I haven't had much time lately, so I haven't properly looked into this yet.
But another difference I noticed is the way the documentation for the type alias is generated here. For `ColorLike` it is generated using `.. autosummary::` (see utilities.rst). I'm not at all a Sphinx expert, so maybe these are equivalent, but maybe you can give this a try?
Additionally, I don't see this typing module being documented on [the deployed documentation for the 'dev' branch](https://docs.pyvista.org/version/dev/api/core/index.html)?