Add `python_display_short_literal_types` option to docs
pyvista/pyvista pull request #5658
Opened 2024-02-21 07:29 UTC by user27182

### Overview

Set [python_display_short_literal_types](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-python_display_short_literal_types) to `True`. This makes `Literal` annotations less verbose. This would affect function signatures like [`connectivity`](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.datasetfilters.connectivity#pyvista.DataSetFilters.connectivity) , for example.

2024-02-21 08:32 UTC, tkoyama010 commented
github-actions preview

2024-02-21 11:21 UTC, tkoyama010 requested changes
Seems to be not working.
https://65d5c387d64de67c2533ffa2--meek-duckanoo-d2f5ec.netlify.app/api/core/_autosummary/pyvista.datasetfilters.connectivity#pyvista.DataSetFilters.connectivity
![Screenshot_20240221-202104](https://github.com/pyvista/pyvista/assets/7513610/592fdb5b-d954-4ff6-a24e-32abc2a00cfe)

2024-02-29 22:24 UTC, tkoyama010 commented
Set this draft until the issue is resolved in the new Sphinx release.

2024-12-04 17:14 UTC, user27182 commented
The sphinx issue for this feature has not yet been resolved. 

Plus, this option is disabled by default in sphinx because it changes valid code in the function signature into invalid code. Perhaps it's best to keep `Literal` in the signatures to avoid confusion and keep it as valid Python.

2024-12-04 17:14 UTC, closed without merging