Allow users to specify Trame Jupyter Mode in environment variable
pyvista/pyvista pull request #5798
Opened 2024-03-19 19:47 UTC by annehaley

### Overview

In environments such as Binder builds, it would be helpful to be able to specify whether to use the `trame_jupyter_extension` with an environment variable. This would reduce the need to reset the configuration manually every time the kernel starts. With these changes, a user may specify `PYVISTA_TRAME_JUPYTER_MODE` in the environment to override the default behavior. If set, accepted values include "extension", "proxy", and "native".

See https://mybinder.org/v2/gh/pyvista/pyvista-xarray/fix-binder?labpath=examples. This Binder build needs to have the `trame_jupyter_extension` enabled. Without it, the plotter iFrames show 404 errors.

### Details

This PR involves one change: the addition of a logic block in the constructor for `pyvista/plotting/themes/_TrameConfig`. If `PYVISTA_TRAME_JUPYTER_MODE` is set, the value will determine how to override the values for `self._server_proxy_enabled` and `self._jupyter_extension_enabled`. If not set, the default values for these are used.

The following table shows how each accepted value affects these attributes, as well as the precondition that must be true for the override to occur.

| PYVISTA_TRAME_JUPYTER_MODE | condition | server_proxy_enabled| jupyter_extension_enabled |
|-----|-----|-----------|------|
|"extension"|extension must be available|False|True|
|"proxy"|proxy must be available|True|False|
|"native"|None|False|False|

2024-03-20 01:09 UTC, tkoyama010 commented on pyvista/plotting/themes.py
> +                self._server_proxy_enabled = False
```suggestion
        # if set, jupyter_mode overwrites defaults
        jupyter_mode = os.environ.get("PYVISTA_TRAME_JUPYTER_MODE")
        if jupyter_mode == "extension" and self._jupyter_extension_available:  # pragma: no cover
            self._server_proxy_enabled = False
            self._jupyter_extension_enabled = True
        elif jupyter_mode == "proxy" and self._server_proxy_enabled:  # pragma: no cover
            self._jupyter_extension_enabled = False
        elif jupyter_mode == "native":  # pragma: no cover
            self._jupyter_extension_enabled = False
            self._server_proxy_enabled = False
```

2024-03-20 01:52 UTC, tkoyama010 requested changes
Thanks for this. Could you add a document about this to `doc/source/user-guide/jupyter/trame.rst`?

2024-03-20 14:26 UTC, annehaley commented
Sure, I added a section to that page in [29e6d75](https://github.com/pyvista/pyvista/pull/5798/commits/29e6d7538daa22bd823ad3bf63b97aa7d79d02a8). Feel free to make any changes to ensure the instructions are clear. Thank you for fixing the coverage failure, too.

2024-03-20 22:57 UTC, tkoyama010 commented on doc/source/user-guide/jupyter/trame.rst
> +If set, the accepted values for `PYVISTA_TRAME_JUPYTER_MODE` include "extension", "proxy", and "native".
```suggestion
If set, the accepted values for `PYVISTA_TRAME_JUPYTER_MODE` include ``'extension'``, ``'proxy'``, and ``'native'``.
```

2024-03-20 22:58 UTC, tkoyama010 commented
@pyvista-bot preview

2024-03-21 23:21 UTC, tkoyama010 approved these changes
LGTM
![Screenshot_20240322-081951](https://github.com/pyvista/pyvista/assets/7513610/814232b5-d691-4249-b696-2a9e3dd80bc8)

2024-03-21 23:21 UTC, merged