Fix `image_threshold` returns incorrect output (all zeros)
pyvista/pyvista pull request #6100
Opened 2024-05-18 17:31 UTC by user27182

Fix issue with `image_threshold` unexpectedly returning all zeros. This seems to be build-specific. I am not able to reproduce this locally but the bug shows up in the docs.

See images of the bug here https://github.com/pyvista/pyvista/pull/6071#issuecomment-2118468493

2024-05-18 18:36 UTC, user27182 commented
From the failed tests it looks like it's a Linux and/or Python < 3.12 issue. The tests fail for some cases with integer inputs.

2024-05-19 05:36 UTC, tkoyama010 requested changes

2024-05-19 05:36 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +        # correctly. Cast to float in these cases.
```suggestion
        # For some systems and Numpy < 2.0, integer scalars won't threshold
        # correctly. Cast to float in these cases.
```

2024-05-19 05:36 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +            self[scalars] = self[scalars].astype(float, casting='safe')
```suggestion
        self[scalars] = self[scalars].astype(float, casting='safe') if cast_dtype
```

2024-05-19 08:46 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +            self[scalars] = self[scalars].astype(float, casting='safe')
This doesn't work closing.

2024-05-19 08:52 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2024-05-19 10:06 UTC, merged