Fix bug of capsule position with vtk<9.3 using non-default parameters
pyvista/pyvista pull request #6119
Opened 2024-05-24 17:00 UTC by kmarchais

### Overview

Fixes #6118 

Using the default center and direction (removing them) for the `CapsuleSource` with 9.0 <= VTK < 9.3 allows to fix the bug as the required center and orientation are used in the `translate` method.

The test was failing with VTK < 9.3 before fixing the bug, it passes after the fix commit.

2024-05-24 17:48 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +def test_capsule_center_corresponds_with_cylinder_center(center, direction):
Briefly name the test and add the URL of this PR for explanation.
```suggestion
# https://github.com/pyvista/pyvista/pull/6119
@pytest.mark.paramatrize('center', [(4, 5, 6), (1, 1, 1)])
@pytest.mark.paramatrize('direction', [(0, 1, -1), (1, 1, 0)])
def test_capsule_center(center, direction):
```

2024-05-24 19:01 UTC, tkoyama010 requested changes

2024-05-24 19:01 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +    assert np.allclose(cylinder.center, center)
```suggestion
    assert np.allclose(cylinder.direction, direction)
```

2024-05-24 23:55 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +    assert np.allclose(capsule.center, center)
Thanks, I change my suggestion.
```suggestion
```

2024-05-24 23:55 UTC, tkoyama010 commented on tests/core/test_geometric_objects.py
> +    assert np.allclose(cylinder.center, center)
```suggestion
```

2024-05-25 02:09 UTC, tkoyama010 commented
pre-commit.ci autofix

2024-05-25 02:11 UTC, tkoyama010 commented
pre-commit.ci autofix

2024-05-25 03:36 UTC, tkoyama010 approved these changes
LGTM

2024-05-25 07:44 UTC, kmarchais commented
Regarding modifying the `CapsuleSource` instead of the `Capsule` function, it appears that the `CapsuleSource` is simply utilizing VTK's implementation. I'm not sure whether this fix should be applied to VTK's `CapsuleSource` or pyvista's.

For now I have left the fix in the `Capsule` function.

2024-05-25 08:20 UTC, tkoyama010 commented
> Regarding modifying the `CapsuleSource` instead of the `Capsule` function, it appears that the `CapsuleSource` is simply utilizing VTK's implementation. I'm not sure whether this fix should be applied to VTK's `CapsuleSource` or pyvista's.
> 
> For now I have left the fix in the `Capsule` function.

I don't see it as a problem as this issue will be resolved once vtk<9.3 support is discontinued. If a user asks a question, let's think about it again.

2024-05-25 09:04 UTC, kmarchais commented
Ok thank you both for the help!

2024-05-25 17:48 UTC, user27182 reviewed
LGTM thanks!

2024-05-25 21:42 UTC, merged