Remove walrus operator to read code in linear flow
pyvista/pyvista pull request #6121
Opened 2024-05-25 14:43 UTC by tkoyama010

### Overview

Fixed a section that was obviously difficult to read due to assignment expressions

@adeak Thanks for your advice.

2024-05-25 17:45 UTC, user27182 commented
Probably a good style rule to avoid use of the walrus operator with ternary if-else blocks. They are indeed a bit confusing to read since the variable must be assigned in the middle of the expression. 

I tried looking for a rule with ruff or similar to enforce this but couldn't find anything.

2024-05-25 17:47 UTC, user27182 submitted a review, later dismissed

2024-05-25 18:33 UTC, adeak requested changes

2024-05-25 18:33 UTC, adeak commented on doc/source/make_tables.py
> +    return doc.splitlines()[0] if (doc) else None
Parentheses were only necessary for the assignment expression:
```suggestion
    return doc.splitlines()[0] if doc else None
```

2024-05-25 18:33 UTC, adeak commented on pyvista/examples/_dataset_loader.py
> +        return sum([1 if os.path.isfile(p) else len(_get_all_nested_filepaths(p)) for p in paths])
Unrelated, but we can use a generator comprehension here
```suggestion
        return sum(1 if os.path.isfile(p) else len(_get_all_nested_filepaths(p)) for p in paths)
```

2024-05-25 18:35 UTC, adeak commented
> Probably a good style rule to avoid use of the walrus operator with ternary if-else blocks. They are indeed a bit confusing to read since the variable must be assigned in the middle of the expression.
> 
> I tried looking for a rule with ruff or similar to enforce this but couldn't find anything.

My recommendation would be to restrict the (mis)feature to the header line of conditional blocks or loops, as a general rule. If there's some consensus about this we could add it to our contributing guide.

2024-05-25 22:04 UTC, adeak approved these changes

2024-05-26 04:30 UTC, user27182 approved these changes

2024-05-26 04:44 UTC, merged