Add `symmetric_bounds` parameter to `AxesGeometrySource`.
pyvista/pyvista pull request #6339
Opened 2024-07-02 23:48 UTC by user27182

### Overview

Follow-up from #6263. This option enables `AxesAssembly` to be used as a widget.

One of the example uses `orientation`, which is added in #6329 .

2024-07-03 04:16 UTC, user27182 commented
@pyvista-bot preview

2024-07-03 16:11 UTC, tkoyama010 requested changes

2024-07-03 16:11 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_sources.py
> +        >>> # Create actors
```suggestion
        Create actors.
```

2024-07-03 16:11 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_sources.py
> +        >>> # Show multi-window plot
```suggestion

        Show multi-window plot.
```

2024-07-03 16:11 UTC, tkoyama010 commented
@pyvista-bot preview

2024-07-04 23:50 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2024-07-04 23:50 UTC, merged