Copy out of range colors to ScalarBars color LookupTable
pyvista/pyvista pull request #6393
Opened 2024-07-18 05:56 UTC by sfladi

### Overview

Correction to the way the color `LookupTable` (LUT) is tranfered from the actor/mappable to the `ScalarBars`, when both `background_color` and `below_range_color` and/or `above_range_color` are specified.

resolves #6390

### Details

- Added manual assignments of `below_range_color` and `above_range_color` to the scalar bar color LookupTable in `ScalarBars.add_scalar_bar()`, as `LookupTable.DeepCopy(...)` [presumably] only handles the underlying VTK implementation.

2024-07-18 13:26 UTC, MatthewFlamm commented
@tkoyama010 I suspect that the caching for the documentation is now broken.   Are you able to clear the cache manually or increment the key in some way to invalidate it for future runs?

2024-07-18 21:00 UTC, tkoyama010 commented
> @tkoyama010 I suspect that the caching for the documentation is now broken. Are you able to clear the cache manually or increment the key in some way to invalidate it for future runs?
> 
> Added: Otherwise we can use the `no-gallery-cache` label, but I suspect we will need to add it to all PRs this way.

I cleared the cache manually. If a similar problem occurs again in the future, I will deal with it.

2024-07-18 21:06 UTC, tkoyama010 requested changes
Thank you for your first contribution. We would like to add a test for this, so could you please provide the sample code that led you to find this bug?

2024-07-18 21:29 UTC, sfladi commented
> Thank you for your first contribution. We would like to add a test for this, so could you please provide the sample code that led you to find this bug?

I basically described this in the issue #6390 under "Steps to reproduce the bug".

But I will provide a more concise example once I am back at my PC.

2024-07-22 07:06 UTC, sfladi commented
Here is a minimal example that produces a visualization including a scalar bar with selected `background_color` and `below_color` as well as `above_color`. We compare the LookupTable out of range colors of the actor and the scalar bar. This fails for the curernt release version of pyvista and succeeds with this merge request.

The code below explicitly calls `pv.Plotter.add_scalar_bar()`, as this function wraps `pv.plotting.scalar_bars.ScalarBars.add_scalar_bar()`), which is where the proposed changes are implemented.

```python
import numpy as np
import pyvista as pv

# parameters
cmap = "viridis"
below_color = "magenta"
above_color = "red"
background_color = "cyan"
data = np.arange(10, dtype=float)
clim = [2.0, 8.0]

# create minimal DataSet
mesh = pv.PointSet(np.stack((data, np.zeros_like(data), np.zeros_like(data)), axis=-1))
mesh["Data"] = data

# visualization
plotter = pv.Plotter()
actor = plotter.add_mesh(
    mesh,
    clim=clim,
    below_color=below_color,
    above_color=above_color,
    copy_mesh=True,
    cmap=cmap,
    show_scalar_bar=False,
)
scalar_bar = plotter.add_scalar_bar(
    mapper=actor.mapper,
    background_color=background_color,
    fill=True,
    outline=True,
)

# compare out of range colors for the actors and the scalar bar
scalar_bar_lut = scalar_bar.GetLookupTable()
assert actor.mapper.lookup_table.below_range_color == scalar_bar_lut.below_range_color
assert actor.mapper.lookup_table.above_range_color == scalar_bar_lut.above_range_color
# plotter.show()
```

2024-07-24 13:40 UTC, sfladi commented
I looked some further into this as the following was unclear to me:

- Why is L446 of `pyvista.plotting.scalar_bars`  implemented in the way that the colors of a transparent scalar_bar are manually "blended" with a specified background color?

- And why does `pv.Plotter.add_scalar_bar` have separate `background_color` and `fill` arguments?

First of all, L446 has no effect on opaque scalar bars, only transparent ones.

Furthermore, any transparent ScalarBar will naturally blend with the background during rendering, making L446 effectively irrelevant, unless `fill=False`.

This leads us to the edge case of `pv.Plotter.add_scalar_bar(..., background_color=some_other_color, fill=False)`:
This apparently allows you to blend a transparent ScalarBar  with `some_other_color`, while not actually adding that color as ScalarBar background. 
This may be usefull in displaying the "true" ScalarBar colors with `background_color="w"` in a render scene, where the render window background is a different color. 
Is that the actually a use case or am I missing something here?

Therefore, my question would be:
- Should the functionality of L446 exclusively be applied for `fill=False`, including extending the background color blending to out of range colors? 
- Or could the functionality of L446 be removed entirely?

2024-07-27 06:58 UTC, user27182 commented
> I looked some further into this as the following was unclear to me:
> 
> * Why is L446 of `pyvista.plotting.scalar_bars`  implemented in the way that the colors of a transparent scalar_bar are manually "blended" with a specified background color?
> * And why does `pv.Plotter.add_scalar_bar` have separate `background_color` and `fill` arguments?
> 
> First of all, L446 has no effect on opaque scalar bars, only transparent ones.
> 
> Furthermore, any transparent ScalarBar will naturally blend with the background during rendering, making L446 effectively irrelevant, unless `fill=False`.
> 
> This leads us to the edge case of `pv.Plotter.add_scalar_bar(..., background_color=some_other_color, fill=False)`: This apparently allows you to blend a transparent ScalarBar with `some_other_color`, while not actually adding that color as ScalarBar background. This may be usefull in displaying the "true" ScalarBar colors with `background_color="w"` in a render scene, where the render window background is a different color. Is that the actually a use case or am I missing something here?

Thank you for your contribution. This is a great analysis of what should be expected from user inputs and the behaviour of the plots. I am not knowledgable enough about the scalar bars to properly respond, but L446 was last modified 3 years ago as part of https://github.com/pyvista/pyvista/commit/b3362c2c5e3f59490c7ec9c13db29469fdc082ff, it's quite possible that there are gaps in the testing and/or implementation. This [comment](https://github.com/pyvista/pyvista/pull/1198#issuecomment-803670692) suggests that there is/was missing test coverage.

> Therefore, my question would be:
> 
> * Should the functionality of L446 exclusively be applied for `fill=False`, including extending the background color blending to out of range colors?
> * Or could the functionality of L446 be removed entirely?

A good way to figure this out is to systematically write test cases (e.g. in [test_scalar_bars.py](https://github.com/pyvista/pyvista/blob/main/tests/plotting/test_scalar_bars.py) or [test_plotting.py](https://github.com/pyvista/pyvista/blob/main/tests/plotting/test_plotting.py)) with the user inputs and expected outputs. Any tests that fail would likely provide an answer to these questions. Or if there are problems/inconsistencies with the API feel free to suggest improvements. Let us know how if there's anything we can do to help.

2026-09-11 15:45 UTC, user27182 commented
Superseded by #9181

2026-09-11 15:45 UTC, closed without merging