Add `CubeFacesSource` for generating a `MultiBlock` with named faces
pyvista/pyvista pull request #6435
Opened 2024-07-29 21:54 UTC by user27182

### Overview

This class inherits from `CubeSource` but modifies the output to generate a `MultiBlock` instead of `PolyData`. 

This class will be used to create a new `LabeledCubeAssembly` class, where each face is labeled.

2024-08-03 06:56 UTC, tkoyama010 requested changes

2024-08-03 06:56 UTC, tkoyama010 commented on pyvista/core/utilities/geometric_sources.py
> +        )
```suggestion
        shrink_factor = self.shrink_factor
        explode_factor = self.explode_factor
        frame_width = self.frame_width
```

2024-08-05 20:48 UTC, tkoyama010 submitted a review, later dismissed
LGTM. Thanks!

2024-08-06 00:37 UTC, user27182 commented on tests/typing/test_bounds_tuple.py
> +            pytest.fail(f"The `bounds` property for class {diff}\n must return a {pv.BoundsTuple}.")
This change is not correct. The aim was to improve the error message, it should say something like:
``` python
f"Class {diff} has a `bounds` property but is not listed as a test case." 
```
I suggest reverting this and leaving this change for another PR.

```suggestion
        assert sorted(class_names) == sorted(expected_names)
```

2024-08-06 00:41 UTC, user27182 commented
The merge with main https://github.com/pyvista/pyvista/pull/6435/commits/23119c254dd6db434d2b0ec75dc86273a4b4a437 failed because `CubeFacesSource` has bounds which is now checked by the tests from #6454. So, `'CubeFacesSource'` just needed to be added to the list of test cases (`CubeFacesSource.bounds` already returns a `BoundsTuple` since it inherits from `CubeSource`).

2024-08-09 15:36 UTC, user27182 commented
> The merge with main [23119c2](https://github.com/pyvista/pyvista/commit/23119c254dd6db434d2b0ec75dc86273a4b4a437) failed because `CubeFacesSource` has bounds which is now checked by the tests from #6454. So, `'CubeFacesSource'` just needed to be added to the list of test cases (`CubeFacesSource.bounds` already returns a `BoundsTuple` since it inherits from `CubeSource`).

No need to add `CubeFacesSource` as a test case anymore since #6470 was merged.

2024-08-10 00:10 UTC, tkoyama010 approved these changes

2024-08-10 01:53 UTC, merged