Simplify code for `fit_plane_to_points`, fix crash with many points, fix returned center
pyvista/pyvista pull request #6517
Opened 2024-08-16 16:51 UTC by user27182

### Overview

Maintenance:
- Simplify code by using `align_xyz` to fit the plane instead of using `np.linalg.svd`
- Update tests to remove the use of magic numbers

Bug fix:
- Fix #6460 (`align_xyz` uses `principal_axes` instead of svd)
- Fix bug with incorrect center returned

2024-08-16 17:16 UTC, user27182 commented on tests/core/test_utilities.py
> -    assert np.allclose(center, [896.9954860028446, 686.6470205328502, 78.13187948615939])
Note that the in the new tests, the returned center does NOT have this value. This means that there was previously a bug with how center was calculated. This is now fixed by this PR (and verified  as correct by the tests)

2024-08-17 04:27 UTC, tkoyama010 requested changes
Need to wait #6521

2024-08-17 20:07 UTC, user27182 commented
I think I'll split this up to keep it maintenance only,  and add features in a separate PR

2024-08-18 05:35 UTC, user27182 commented
I think this may be a breaking change in the sense that the direction of the normal may be flipped between the old implementation and the new one. Any code fitting a plane, then relying on this plane for signed distance calcs or for clipping a dataset would now silently return a different result. 

Do we need a warning in the docs, or just a versionchanged directive?

2024-08-18 05:46 UTC, tkoyama010 commented
Please add a warning in the docs.

2024-08-20 20:51 UTC, user27182 commented
Keeping this as draft based on this comment: https://github.com/pyvista/pyvista/issues/6460#issuecomment-2299735699
I want to explore keeping SVD as an option for computing the principal axes

2024-08-21 20:54 UTC, user27182 commented
> I want to explore keeping SVD as an option for computing the principal axes

This is explored here: https://github.com/pyvista/pyvista/issues/6460#issuecomment-2302993313. We should not use SVD. This is ready for review as-is.

2024-08-21 22:42 UTC, tkoyama010 approved these changes
LGTM

2024-08-22 06:32 UTC, merged