Add HSV-sorted color table to docs
pyvista/pyvista pull request #6594
Opened 2024-08-30 23:48 UTC by user27182

### Overview

Show colors sorted by HSV in a separate dropdown. This presents an alternative way of viewing the colors. The sorted is the same as used in matplotlib here https://matplotlib.org/stable/gallery/color/named_colors.html#css-colors

2024-08-31 00:23 UTC, user27182 commented on doc/source/make_tables.py
> +    SortedColorTable.generate()
For debugging only, remove later

2024-08-31 23:05 UTC, tkoyama010 requested changes

2024-08-31 23:05 UTC, tkoyama010 commented on pyvista/plotting/colors.py
> +    .. dropdown:: Colors Sorted By Name
```suggestion
    .. dropdown:: Colors Sorted by Name
```

2024-08-31 23:05 UTC, tkoyama010 commented on pyvista/plotting/colors.py
> +    .. dropdown:: Colors Sorted By Hue, Saturation, and Value
```suggestion
    .. dropdown:: Colors Sorted by Hue, Saturation, and Value
```

2024-08-31 23:05 UTC, tkoyama010 commented on pyvista/plotting/colors.py
> +        .. dropdown:: Colors Sorted By Name
```suggestion
        .. dropdown:: Colors Sorted by Name
```

2024-08-31 23:05 UTC, tkoyama010 commented on pyvista/plotting/colors.py
> +        .. dropdown:: Colors Sorted By Hue, Saturation, and Value
```suggestion
        .. dropdown:: Colors Sorted by Hue, Saturation, and Value
```

2024-08-31 23:06 UTC, tkoyama010 submitted a review, later dismissed
LGTM

2024-09-01 01:28 UTC, tkoyama010 approved these changes

2024-09-01 05:12 UTC, merged