Fix_`cast_to_rectilinear_grid`_rounding_error
pyvista/pyvista pull request #6656
Opened 2024-09-16 16:52 UTC by GuillaumeBroggi

The current implementation can introduce a floating-point error when the `spacing` is a float.

For instance, the following would fail:
```python
import pyvista as pv

grid = pv.ImageData(
    dimensions=(10, 10, 10),
    spacing=(27.88888888888889, 28.11111111111111, 28.22222222222222),
    origin=(-126.0, -127.0, -127.0),
)
rectilinear = grid.cast_to_rectilinear_grid()
assert rectilinear.bounds == grid.bounds
```

The proposed PR uses `np.linspace` to generate the rectilineat coordinates, to generate rectilinear coordinates, so floating-point errors are not accumulated.

2024-09-16 21:21 UTC, tkoyama010 commented on tests/core/test_grid.py
> +    grid = pv.ImageData(
```suggestion
    # https://github.com/pyvista/pyvista/pull/6656
    grid = pv.ImageData(
```

2024-09-16 21:22 UTC, tkoyama010 approved these changes
LGTM

2024-09-17 08:02 UTC, GuillaumeBroggi commented
As a side note, the proposed PR does not degrade performances.

```python
%%timeit
grid = pv.ImageData(
    dimensions=(10000, 10000, 10000),
    spacing=(27.88888888888889, 28.11111111111111, 28.22222222222222),
    origin=(-126.0, -127.0, -127.0),
)
rectilinear = grid.cast_to_rectilinear_grid()
```
Current implementation:
> `446 μs ± 10.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)`
Proposed PR:
> `304 μs ± 2.37 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)`

2024-09-17 10:08 UTC, tkoyama010 commented
Glad to hear it :)

2024-09-17 14:26 UTC, MatthewFlamm approved these changes
Thanks!  This would be better without the unrelated formatting changes however.  If the formatting needs to be changed in this file it would be better in a separate PR.

2024-09-17 15:07 UTC, GuillaumeBroggi commented
@MatthewFlamm Good point; I did not notice the formatting changed; that's a mistake. I'll correct it. Thanks!

2024-09-17 17:49 UTC, user27182 commented
Looks like the use of single quotes for the formatting may be preferred for the project. See #6657.

2024-09-17 17:52 UTC, tkoyama010 requested changes
OK. Let's wait for it.

2024-09-17 20:56 UTC, GuillaumeBroggi commented
It should be fixed now. I had unintentionally applied black formatter.

2024-09-17 22:07 UTC, tkoyama010 approved these changes

2024-09-17 22:33 UTC, MatthewFlamm approved these changes

2024-09-18 01:07 UTC, merged