Add fine grain execution control for pyvista-plot directive
pyvista/pyvista pull request #6700
Opened 2024-10-11 22:52 UTC by bjlittle

### Overview

This pull-request adds some fine grain options to control the execution of the `pyvista-plot` directive.

#### Motivation

Building documentation can be expensive, particularly if it's image rich, which is pretty much the accepted norm here. However, sometimes as a developer there is a need for a slicker workflow experience when changing the documentation i.e., change the docs, build the docs, review the rendered docs ... typically this can involve several rinse'n repeat iterations, but the major bottleneck is always the documentation build time.

I'm proposing a couple of minor changes that will hopefully give developers the ability to improve the turnaround of their documentation changes by rendering only images of their particular interest, which may be none, some or all.

#### Implementation

##### Options

The `pyvista-plot` directive has the following **new** options:

- `:skip:` which has an optional boolean argument i.e., `yes`, `1`, `true`, `no`, `0`, `false`. If no argument is provided, then it is assumed to the enabled e.g., `:skip:` is equivalent to `:skip: yes`. The purpose of this option is to override the behaviour of the `plot_skip` configuration variable, and enforce the execution of the directive or not
- `:optional:` which is a flag (no argument). The purpose of this option is to mark a directive for conditional execution, which is controlled by the state of the `plot_skip_optional` configuration variable.

##### `conf.py`

The `pyvista-plot` directive has the following **new** configuration variables:

- `plot_skip` is a boolean. Default is `False`. This variable is used to seed the value of any directive that doesn't explicitly specify a `:skip:` option
- `plot_skip_optional` is a boolean. Default is `False`. This variable is used to control whether any directive marked with an `:optional:` flag is executed or not

#### Workflow

Note that, given the default values of the **new** `conf.py` configuration variables there is no change in the existing behaviour of the `pyvista-plot` directive.

Here are some example workflows that are now easily possible:

- disable all `pyvista-plot` directives with `plot_skip = True` in the `conf.py`
- disable all `pyvista-plot` directives with `plot_skip = True` apart from one (or more) marked with `:skip: no`
- execute all `pyvista-plot` directives with `plot_skip = False` and `plot_skip_optional = False` (default behaviour)
- execute all `pyvista-plot` directives with `plot_skip = False` apart from one (or more) marked with `:optional:` because `plot_skip_optional = True`

Note that, skipped `pyvista-plot` directives will still have their code blocks rendered.

2024-10-11 22:58 UTC, bjlittle commented
pre-commit.ci autofix

2024-10-12 03:10 UTC, tkoyama010 requested changes

2024-10-12 03:10 UTC, tkoyama010 commented on pyvista/ext/plot_directive.py
> +    nofigs : None
ref https://numpydoc.readthedocs.io/en/stable/format.html#parameters
```suggestion
    nofigs : bool, default None
```

2024-10-12 03:10 UTC, tkoyama010 commented on pyvista/ext/plot_directive.py
> +    force_static : None
```suggestion
    force_static : bool, default None
```

2024-10-12 03:10 UTC, tkoyama010 commented on pyvista/ext/plot_directive.py
> +        ``False``.
```suggestion
    plot_skip : bool, default False
        Default value for the ``skip`` directive option.
```

2024-10-12 03:10 UTC, tkoyama010 commented on pyvista/ext/plot_directive.py
> +
```suggestion

    plot_skip_optional : bool, default False
        Whether to skip execution of ``optional`` directives.

```

2024-10-13 09:38 UTC, tkoyama010 requested changes
Thank you for the change. It would be grateful if you could add a test to the `tests/test_tinypages.py` so that we can understand the specific use of this change.

2024-10-16 20:53 UTC, bjlittle commented
@tkoyama010 `uber/h3-py` have just release a breaking major 4.x release ... patching `geovista` now :+1:

2024-10-16 20:53 UTC, bjlittle commented
pre-commit.ci autofix

2024-10-16 22:08 UTC, bjlittle commented
@tkoyama010 Back to you :+1: 

I've updated the test coverage as you requested. Hopefully this helps.

If you have any further questions then please don't hesitate to ask.

Also, I appear to now have a failing `Vale` CI tests ... not quite sure how to fix that. Can you advise please :pray:

2024-10-16 22:26 UTC, bjlittle commented
Ahhh the same `vale` barf appears to be happening with other pull-requests e.g., #6707

So there seems to be a systemic failure here, but since I don't use and understand `vale` not quite sure what to do ...

2024-10-17 10:59 UTC, tkoyama010 commented
> Ahhh the same `vale` barf appears to be happening with other pull-requests e.g., #6707
> 
> So there seems to be a systemic failure here, but since I don't use and understand `vale` not quite sure what to do ...

It is resolved in #6708 .

2024-10-20 12:12 UTC, bjlittle commented
@tkoyama010 Okay, back to you as the `vale` CI job seems to be behaving itself again.

Thanks :+1:

2024-10-21 13:19 UTC, tkoyama010 approved these changes
LGTM

2024-10-21 15:07 UTC, merged

2024-10-21 15:24 UTC, bjlittle commented
@tkoyama010 Awesome! Thanks! Much appreciated :beers: :partying_face: :tada: