Deprecate `ActiveArrayInfo` and use `ActiveArrayInfoTuple` directly
pyvista/pyvista pull request #6835
Opened 2024-11-21 20:10 UTC by user27182

### Overview

The `ActiveArrayInfo` class is just a wrapper for a named tuple. Its repr, getitem, and iter methods all wrap the named tuple methods directly. This is problematic for type checking since unpacking the tuple this way will result in all items of the tuple having the same unionized type. So, the type of  the unpacked `association` and `name` fields are ambiguous.

It's better to just use the `NamedTuple` class directly. In this PR the copy method is moved to `ActiveArrayInfoTuple` but otherwise none of the other methods are needed and can later be removed.

2024-11-21 22:56 UTC, bjlittle commented
@user27182 Re-ran the failing `Integration Tests / GeoVista` after merging [PR#1219](https://github.com/bjlittle/geovista/pull/1219) on `geovista`, and you're unblocked, thanks :+1:

2024-12-02 21:16 UTC, tkoyama010 requested changes

2024-12-02 21:16 UTC, tkoyama010 commented on tests/core/test_dataset.py
> +        if pv._version.version_info >= (0, 48):
See #6850 and #6862.
```suggestion
        if pv._version.version_info[:2] > (0, 48):
```

2024-12-02 21:44 UTC, tkoyama010 approved these changes
LGTM

2024-12-02 22:24 UTC, tkoyama010 approved these changes

2024-12-03 06:16 UTC, tkoyama010 approved these changes

2024-12-03 09:41 UTC, merged