Format docstring with ruff
pyvista/pyvista pull request #6991
Opened 2024-12-16 22:07 UTC by beroda

### Overview

Guess what ... ruff can ~make coffee :coffee:~ format docstrings https://docs.astral.sh/ruff/formatter/#docstring-formatting

Let's try out ...

2024-12-16 22:09 UTC, beroda commented on pyvista/_plot.py
> +    >>> grid = pv.ImageData(dimensions=(32, 32, 32), spacing=(0.5, 0.5, 0.5))
Lines are wrapped more consistently than with blackdoc (length is 69 < limit of 75)

2024-12-16 22:43 UTC, user27182 commented
+1 for using `ruff` generally.
See also https://github.com/pyvista/pyvista/pull/6467#issuecomment-2272536196
There were previously concerns with `ruff` not formatting `rst` and `md` files

2024-12-17 00:38 UTC, user27182 commented
The ruff [configuration](https://docs.astral.sh/ruff/configuration/) states:

> Enable auto-formatting of code examples in docstrings. Markdown,
reStructuredText code/literal blocks and doctests are all supported.

Maybe I'm missing something but if markdown is supported, shouldn't it format this code block to use single quotes?
https://github.com/pyvista/pyvista/blob/6e59ba2115416e82c5994fce5abb6c5be271bbfc/CONTRIBUTING.rst?plain=1#L430-L437

But I'm not seeing `CONTRIBUTING.md` in the diff for this PR... There are also no `rst` files listed either, not sure if there are any codeblocks anywhere that _should_ be picked up, but still... makes me think `rst` files aren't covered either. 

Also, the current `blackdoc` config seems not to be working? Because if I try running `blackdoc CONTRIBUTING.rst`, this _does_ seem to work, but it errors out (it tries formatting bash code blocks and can't). But this clearly isn't the case with our current blackdoc config.


So, I'm +1 with this PR and dropping blackdoc and using ruff. But we should still figure out how to fill the gap and format code in `rst` and `md` files

2024-12-17 08:57 UTC, beroda commented
> The ruff [configuration](https://docs.astral.sh/ruff/configuration/) states:
> 
> > Enable auto-formatting of code examples in docstrings. Markdown,
> > reStructuredText code/literal blocks and doctests are all supported.
> 
> Maybe I'm missing something but if markdown is supported, shouldn't it format this code block to use single quotes?

I agree that the ruff documentation is a bit misleading on this topic. I think they mean that ruff can format `Markdown` and `rst` python code blocks that are **inside the docstring of functions**. The examples in the configuration speak for themselves.
https://docs.astral.sh/ruff/settings/#format_docstring-code-format

> So, I'm +1 with this PR and dropping blackdoc and using ruff. But we should still figure out how to fill the gap and format code in `rst` and `md` files

I guess this gap will be filled once https://github.com/astral-sh/ruff/issues/8237 and https://github.com/astral-sh/ruff/issues/3792 are solved.

2024-12-17 13:06 UTC, beroda commented
This PR should be merged after https://github.com/pyvista/pyvista/pull/6994 to be compatible.
Move to draft.

2024-12-19 22:28 UTC, tkoyama010 requested changes

2024-12-19 22:28 UTC, tkoyama010 commented on pyproject.toml
> +
```suggestion
```

2024-12-19 22:29 UTC, tkoyama010 approved these changes
LGTM

2024-12-20 19:11 UTC, merged