Remove warning ignore for depreciated
pyvista/pyvista pull request #7009
Opened 2024-12-20 10:12 UTC by beroda

### Overview

`pytest` suggests to not ignore depreciation warnings to avoid future breakage.
https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html#deprecationwarning-and-pendingdeprecationwarning

Moreover, turning all warnings to errors might also catch some subtle errors (unclosed files reading ...).

2024-12-20 13:22 UTC, beroda commented on pyproject.toml
> +  'ignore:Points is not a float type.*:UserWarning',
Added since happens during test collection. Planning to remove later

2024-12-20 13:23 UTC, beroda commented on pyvista/core/pointset.py
> +        return tuple(dims)
Depreciation from vtk 9.3

2024-12-20 13:23 UTC, beroda commented on tests/core/test_utilities.py
>      assert np.allclose(axes, DEFAULT_PRINCIPAL_AXES)
The test is intentionally with an empty slice. Ok to ignore

2024-12-20 13:24 UTC, beroda commented on tests/core/test_validation.py
> +)
Not sure to understand this deprecation. Need bit of digging ...

2024-12-20 13:39 UTC, beroda commented on tests/plotting/test_camera.py
> +    thickness = np.random.default_rng().random()
0 dim arrays treated as scalars, from numpy 1.25 deprecation https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations, https://github.com/numpy/numpy/pull/10615

2024-12-20 20:52 UTC, user27182 commented
`INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: image_cache_dir`

This option is defined in `[tool.pytest.ini_options]` and is used by `pytest-pyvista` for units tests.

It's technically not needed or used for running the `tst_doc_images` test though. Not sure if there's a way to optionally include it only if `pytest-pyvista` is installed.

If not, I think we can just add `pytest-pyvista` as a `docs` dependency in `pyproject.toml` to get rid of the warning

2025-01-07 16:09 UTC, beroda commented on pyvista/plotting/lookup_table.py
> +    def __array_wrap__(self, out_arr, context=None, return_scalar: bool = False):  # type: ignore[override]
Needed due to numpy 2.0 deprecation here https://github.com/numpy/numpy/pull/25409

2025-01-07 16:45 UTC, beroda commented
> `INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: image_cache_dir`
> 
> This option is defined in `[tool.pytest.ini_options]` and is used by `pytest-pyvista` for units tests.
> 
> It's technically not needed or used for running the `tst_doc_images` test though. Not sure if there's a way to optionally include it only if `pytest-pyvista` is installed.
> 
Warning is ignored in https://github.com/pyvista/pyvista/pull/7009/commits/ebec004bb8ce21772b6da7ed372aaf10a40c47c5

2025-01-07 16:56 UTC, user27182 commented on tests/core/test_validation.py
> +)
I think this test is checking for exactly the kind of incorrect behavior that has been deprecated, i.e. that `np.dtype(np.number)` returns `float64` unexpectedly.

This succeeds:
``` python
check_subdtype([1, 2, 3], np.number)
```
but this fails (unexpectedly):
``` python
check_subdtype([1, 2, 3], np.dtype(np.number))
```

Maybe we should remove this test altogether? I think it was written because of this odd behavior, but if it's deprecated, then this "feature" should no longer get used and so we don't need to worry about it (or test for it)

2025-01-08 22:08 UTC, beroda commented on pyvista/plotting/cube_axes_actor.py
> +
Due to vtk 9.3 deprecation [here](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10072/diffs?file=829994b49e505c707ee9776d6359808d737edfad#829994b49e505c707ee9776d6359808d737edfad_172_177)

2025-01-08 22:32 UTC, beroda commented on pyproject.toml
> +  'ignore:pyvista test generated image dir.* does not yet exist.  Creating dir.:UserWarning',
Harmless ignore since the warning is only to inform the user a folder is being created by pytest-pyvista

2025-01-08 22:48 UTC, beroda commented on pyproject.toml
> +  'ignore:pyvista test generated image dir.* does not yet exist.  Creating dir.:UserWarning',
Harmless ignore since the warning is only to inform the user a folder is being created by pytest-pyvista

2025-01-08 22:49 UTC, beroda commented on pyproject.toml
> +  'ignore:Points is not a float type.*:UserWarning',
Added since warning raised during test collection. Planning to remove later

2025-01-09 21:13 UTC, beroda commented on pyvista/plotting/plotter.py
> +            and not self.render_window.GetRenderFramebuffer().GetFBOIndex()  # type: ignore[union-attr]
Deprecated from vtk 9.1. See removal in 9.3 [here](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9300/diffs#diff-content-6cf09b948f42b890a33c2e2222778843b8b87810) and [here](https://docs.vtk.org/en/latest/release_details/9.3.html#legacy)

2025-01-10 14:00 UTC, beroda commented on tests/core/test_validation.py
> +    'ignore:Creating an ndarray from ragged nested sequences:numpy.VisibleDeprecationWarning'
Warning is already catched inside the _cast_to_numpy call

2025-01-10 14:02 UTC, beroda commented on tests/core/test_validation.py
> +)
Sorry, I am not really sure to understand everything. Feel free to propose changes on the PR, as I don't fully master the validation module (yet).

2025-01-10 18:03 UTC, beroda commented on pyvista/plotting/cube_axes_actor.py
> +
Due to vtk 9.3 deprecation [here](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10072/diffs?file=829994b49e505c707ee9776d6359808d737edfad#829994b49e505c707ee9776d6359808d737edfad_172_177)

2025-01-12 13:53 UTC, beroda commented on tests/conftest.py
> +def marker_names(item: pytest.Item):
Added in pytest_configure for two reasons:

- To ignore warning depending on vtk version
- Because the warning is emitted during test collection, ie. before `pytest_collection_modifyitems`

2025-01-12 13:55 UTC, beroda commented on tests/conftest.py
> +
All tests in the `plotting` module always show the warning

2025-01-12 19:47 UTC, beroda commented on tests/conftest.py
> +        )
Added in pytest_configure for two reasons:

-  To ignore warning depending on vtk version
- Because the warning is emitted during test collection, ie. before pytest_collection_modifyitems

2025-01-12 19:47 UTC, beroda commented on tests/conftest.py
> +        )
Added here because the warning is emitted during test collection, ie. before `pytest_collection_modifyitems`

2025-01-13 06:02 UTC, user27182 commented on tests/conftest.py
> +
> I originally planned to add this filter to `pyproject.toml`, but the reorder arrays from `taplo` in `pre-commit` places the `always` before the `error`, therefore the warning is converted to an error since pytest is applying the latest filter that matches (see the doc below).

you can add a newline between sections and taplo will then sort the two sections independently, should be able get `'errors'` above `'always'` that way

2025-01-15 20:54 UTC, tkoyama010 requested changes

2025-01-15 20:54 UTC, tkoyama010 commented on pyvista/plotting/plotter.py
> +                raise ValueError('Invoking helper with no framebuffer')
```suggestion
        if hasattr(renwin := self.render_window, attr) and not getattr(renwin, attr)().GetFBOIndex():
            # must raise a runtime error as this causes a segfault on VTK9
            raise ValueError('Invoking helper with no framebuffer')
```

2025-01-15 21:01 UTC, tkoyama010 commented
pre-commit.ci autofix

2025-01-16 23:32 UTC, user27182 approved these changes
This all looks great, thanks! Just have a few minor nits. I think we should address the missing test coverage though.

2025-01-16 23:32 UTC, user27182 commented on tests/conftest.py
> +        )
```suggestion
    if any(Path(a).stem == 'tst_doc_images' for a in config.args):
        # Warning is emitted because `pytest-pyvista` is not installed (and is not required for this test)
        warnings.append(
            'ignore:Unknown config option.*image_cache_dir.*:pytest.PytestConfigWarning'
        )
```

2025-01-16 23:32 UTC, user27182 commented on tests/core/test_utilities.py
> +class Cases_transform_apply:
nit: I don't think we have a documented convention but this formatted is more consistent with our class definitions
```suggestion
class CasesTransformApply:
```

2025-01-16 23:32 UTC, user27182 commented on tests/core/test_validation.py
> +)
Like other tests the emitted warning is part of the reason it's being tests as this is an edge case. So it's fine to ignore the warning here.

2025-01-16 23:32 UTC, user27182 commented on pyvista/plotting/cube_axes_actor.py
> +            return offx, offy  # type: ignore[return-value]
This branch (and others in this module) are not tested... but this change in output is non-trivial, I think we should add tests here for these branches.

2025-01-17 17:20 UTC, user27182 approved these changes

2025-01-18 03:49 UTC, tkoyama010 approved these changes
LGTM

2025-01-18 07:46 UTC, merged

2025-01-18 18:07 UTC, user27182 commented
Looks like this warning was missed:
https://github.com/pyvista/pyvista/actions/runs/12846211834/job/35821145026?pr=7100#step:9:28
```
E   UserWarning: Unable to access C:\Users\runneradmin\AppData\Local\pyvista_3\pyvista_3\Cache. Manually specify the PyVistaexamples cache with the PYVISTA_USERDATA_PATH environment variable.
```
This happens sometimes because of how the caching works, so errors are only caught post-merge.

2025-01-18 19:27 UTC, user27182 commented on pyproject.toml
> +  'error',
This line broke debugging for me in PyCharm. If I add breakpoints, the execution isn't stopped anymore. If I comment out this line though, debugging with breakpoints works again.

2025-01-18 20:50 UTC, beroda commented
> Looks like this warning was missed: https://github.com/pyvista/pyvista/actions/runs/12846211834/job/35821145026?pr=7100#step:9:28
> 
> ```
> E   UserWarning: Unable to access C:\Users\runneradmin\AppData\Local\pyvista_3\pyvista_3\Cache. Manually specify the PyVistaexamples cache with the PYVISTA_USERDATA_PATH environment variable.
> ```
> 
> This happens sometimes because of how the caching works, so errors are only caught post-merge.

Yes, I also noticed it once [here](https://github.com/pyvista/pyvista/actions/runs/12846211834/job/35821145026?pr=7100#step:9:28) but it disappeared in the next CI runs so I thought it was a flaky behavior.

We can open a new PR to include the warning I guess.

2025-01-18 20:52 UTC, beroda commented on pyproject.toml
> +  'error',
Sorry to hear that.

I am not a PyCharm user so I could not see the issue. On my side, VSCode works fine with these settings.

Does it happen for any python code or specifically with the tests ?

2025-01-18 22:04 UTC, user27182 commented on pyproject.toml
> +  'error',
I created a new Codespace and can reproduce the issue there. To reproduce:

1. Create a new Codespace from main
2. Add a breakpoint to a test file, e.g. add one at the top of the file at one of the import statements.
3. Start debugging any test in the test file. Execution is expected to stop at the breakpoint but it doesn't. The test will still run to completion though and pass.

Workaround to fix this:

1. Comment out or remove `'error'` from `filterwarnings`
2. Debug the tests again. Execution should stop at the breakpoint (as expected).

This is a very peculiar issue, maybe it's a `pytest` bug?

2025-01-19 18:00 UTC, beroda commented on pyproject.toml
> +  'error',
I was able to reproduce the behavior on VScode. I guess a matplotlib warning is emitted by the python debugger. 

Try add that in the `pyproject.toml`
```suggestion
'ignore:The .*interactive_bk.* attribute was deprecated in Matplotlib 3\.9.*:matplotlib.MatplotlibDeprecationWarning',
```

It fixed breakpoints on my side