Add new `color_labels` filter to add color scalars to labeled data
pyvista/pyvista pull request #7024
Opened 2024-12-27 21:56 UTC by user27182

### Overview

This filter can be used for coloring non-contiguous labeled data. It is well-suited to segmentation applications where labelmaps are commonly used. In part, this filter overcomes the limitations of using `categorical=True` with the plotter, see #5994.

As a follow-up, this can be used to improve the examples for the `contour_labels` filter, see https://github.com/pyvista/pyvista/pull/6732#discussion_r1869899480

2025-01-04 04:31 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +        colors_name = name + '_rgba' if output_scalars is None else output_scalars
if `color_type` is `float_rgb` or `int_rgb`, should `_rgb` be appended to the array name in these cases instead of `_rgba` ?

2025-01-04 17:16 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +        colors_name = name + '_rgba' if output_scalars is None else output_scalars
fixed in [cd6a05f](https://github.com/pyvista/pyvista/pull/7024/commits/cd6a05f2fbc4fc2df26d9b4f419d7033fbc67fe5)

2025-01-05 08:05 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +        preference : str, default: "point"
Might make more sense for `'cell'` to be the default.
```suggestion
        preference : str, default: "cell"
```

2025-01-05 22:42 UTC, tkoyama010 requested changes

2025-01-05 22:42 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +                if min_ >= 0 and max_ <= max_value:
```suggestion
                if 0 <= min and max_ <= max_value:
```

2025-01-05 23:47 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +                if min_ >= 0 and max_ <= max_value:
This is linted by ruff to have the constant on the right:
https://docs.astral.sh/ruff/rules/yoda-conditions/

We can `noqa` it though, it does make sense here to have consistent operators

2025-01-05 23:55 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +        preference : str, default: "point"
cell is now the default [0ea8d97](https://github.com/pyvista/pyvista/pull/7024/commits/0ea8d973098d8b883962619edc753b2ef112f8ef)

2025-01-06 03:34 UTC, tkoyama010 requested changes

2025-01-06 03:34 UTC, tkoyama010 commented on pyvista/core/filters/data_set.py
> +        >>> image_labels = image_labels.extract_subset(voi=(75, 109, 75, 109, 85, 100))
Would it be possible to plot the dataset at this stage to provide a clearer understanding of the filter's behavior?

2025-01-06 03:57 UTC, user27182 commented on pyvista/core/filters/data_set.py
> +        >>> image_labels = image_labels.extract_subset(voi=(75, 109, 75, 109, 85, 100))
An example with the default coloring applied by the plotter is added in [d4f9e44](https://github.com/pyvista/pyvista/pull/7024/commits/d4f9e4496e4256ff2f514623fa46d914540c4110)

Still need to update the doc image cache but should be good to go.

2025-01-06 08:33 UTC, tkoyama010 approved these changes
LGTM

2025-01-06 08:33 UTC, merged