Fix default param's value in docs in data_set.py
pyvista/pyvista pull request #7027
Opened 2024-12-28 21:35 UTC by dad616610

### Overview

The default value of the function parameter  `inplace` in `transform` function is `True`: https://github.com/pyvista/pyvista/blob/57f40202a8d4bb2315a79d088746dc1a04676cf1/pyvista/core/filters/data_set.py#L7022
 while the docs say it's `False`: https://github.com/pyvista/pyvista/blob/57f40202a8d4bb2315a79d088746dc1a04676cf1/pyvista/core/filters/data_set.py#L7066

This PR makes the docs mirror the code's behaviour:
```diff
-       inplace : bool, default: False 
+       inplace : bool, default: True
```

But maybe, the default value of the function parameter should be changed to `False` instead?
```diff
- inplace: bool = True, 
+ inplace: bool = False,
```

2024-12-28 23:08 UTC, tkoyama010 requested changes
The documentation is correct on this. In other functions, when we want to inplace, we specify it explicitly.
Could you also add code to test for this bug?

2024-12-29 23:07 UTC, darikg commented
> The documentation is correct on this. In other functions, when we want to inplace, we specify it explicitly. Could you also add code to test for this bug?

@tkoyama010 could you clarify this? I think @dad616610 is simply proposing to to update the documentation to reflect actual behavior, are you suggesting changing the behavior to reflect the documentation? I support that but it's a more significant PR involving deprecation cycles, etc.

2025-01-01 15:23 UTC, tkoyama010 commented
> > The documentation is correct on this. In other functions, when we want to inplace, we specify it explicitly. Could you also add code to test for this bug?
> 
> @tkoyama010 could you clarify this? I think @dad616610 is simply proposing to to update the documentation to reflect actual behavior, are you suggesting changing the behavior to reflect the documentation? I support that but it's a more significant PR involving deprecation cycles, etc.

Thank you for your comment. Regarding this, I am thinking that it is a simple bug and just FIX the behavior. If additional action is needed, I would appreciate your input on that.

2025-01-04 13:49 UTC, MatthewFlamm commented
I thought we aligned on having `inplace` always default to False`, but I can't find that.  There is a discussion on removing `inplace` entirely in #4158, but there was no consensus.

I'm a believer in consistency in the API being a high priority.  Nearly every other place uses a default of `False`.  The decision in my mind is whether to do a hard breaking change or a softer one where we transition the default over multiple versions.  While the documentation is what I/we want, there are likely users currently using the existing code.

Thanks for finding this!

2025-01-04 23:36 UTC, user27182 commented
> I thought we aligned on having `inplace` always default to False`, but I can't find that.

Maybe this? https://github.com/pyvista/pyvista/pull/1860

Haven't read through it but at first glance this seems to suggest that `inplace=True` is a bug (not a breaking change) and that all transformations should _not_ be inplace.

2025-01-07 17:56 UTC, MatthewFlamm commented
I'm +1 for merging this one.  Since we are likely deprecating the behavior, the behavior is currently default `True`.  It makes sense that the documentation reflects this now.  @darikg will likely have to fix a small merge conflict if we do it.  As long as they are ok with that,  I think merging this makes sense.

2025-01-07 18:02 UTC, user27182 approved these changes

2025-01-07 18:08 UTC, MatthewFlamm approved these changes

2025-01-07 23:32 UTC, tkoyama010 approved these changes

2025-01-08 06:14 UTC, merged