Add multi-component scalars output option to `contour_labels`
pyvista/pyvista pull request #7033
Opened 2024-12-30 08:07 UTC by user27182

### Overview

This filter outputs 2-component scalars by default. But this is only useful when internal boundaries are generated (which are not by default) and can be problematic for plotting since the `norm` is shown by default (and therefore requires care to plot these scalars correctly).

This PR adds the option to output _either_ a one- or two-component array. The default behavior is to output a single-component array for `external` boundaries, and a two-component array for the `all` and `internal` cases. This greatly simplifies the default behavior for generating external contours, since the input image and output surface of this filter will both have matching single-component labels.

2025-01-03 00:18 UTC, user27182 reviewed
Possible improvements.

2025-01-03 00:18 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +        multi_component_output : bool, optional
Could rename this to `simplify_output` to make it a bit clearer that this is what's happening.

2025-01-03 00:18 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +            is ``'external'``, and ``True`` otherwise.
We can change the default to always output a 2-component array. The option to simplify to 1D array would then need to be explicitly set as a kwarg in all cases.

2025-01-03 00:18 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +              simplified by computing the vector norm of the values.
This simplification is not ideal.
1. I think any simplification should probably generate integer values since we are dealing with categorical data. 
2. using `norm` is bad because of perfect triangles, e.g. the boundary label `[3 4]` is mapped to `5`, but this value could already be assigned to a separate foreground region `5`.

Maybe simply labelling internal boundaries sequentially with negative values is better. e.g. `[1 2] -> -1`, `[1 3] -> -2`, etc. We still lose information about _which_ regions each cell is bound to, but this way the values are unique integers and won't clash with existing foreground regions which are positive

2025-01-03 10:29 UTC, tkoyama010 requested changes

2025-01-03 10:29 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +        multi_component_output : bool, optional
This is exactly what I was thinking. With `multi_component_output` it was unclear to me.

2025-01-03 17:58 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +              simplified by computing the vector norm of the values.
This new negative integer mapping is implemented in [5b37bbb](https://github.com/pyvista/pyvista/pull/7033/commits/5b37bbb3f6b63234fb036e552fdd9382e0021b41)

2025-01-03 17:59 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +            is ``'external'``, and ``True`` otherwise.
I do think simplifying by default is a good thing to keep. So this change is not currently planned.

2025-01-03 18:06 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +        >>> contours['boundary_labels'] += 20
This is only needed temporarily for this PR. This seemingly arbitrary assignment is removed with #7051.

2025-01-04 03:36 UTC, tkoyama010 requested changes
All reviews have been completed. I will merge them after resolving the comments.

2025-01-04 03:36 UTC, tkoyama010 commented on tests/core/test_imagedata_filters.py
> +    assert poly[BOUNDARY_LABELS].ndim == 2
I think it will be easier to understand if we parametrize this with `simplify_output`.

2025-01-04 03:36 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +                    is_internal = np.all(labels_array != background_value, axis=1)
```suggestion
                is_internal = np.full((output.n_cells,), True) if boundary_style == 'internal' else np.all(labels_array != background_value, axis=1)
```

2025-01-04 03:36 UTC, tkoyama010 commented on pyvista/core/filters/image_data.py
> +              values is not fixed, and can change depending on the input.
It would be more helpful to clearly specify the benefits or implications of modifying the value to a negative number. I understand the advantage of being able to clear the internal value by displaying only values greater than zero, but this wasn’t immediately clear to me at first.

2025-01-04 03:50 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +              values is not fixed, and can change depending on the input.
Above the bullet points this statement is made:
> This simplification is useful when only external boundaries
>  are generated and/or when visuallizing internal boundaries.

Maybe we can move this around to the bullet points?

2025-01-04 05:44 UTC, user27182 commented on pyvista/core/filters/image_data.py
> +              values is not fixed, and can change depending on the input.
Added info about benefits of negative values in [1f98c47](https://github.com/pyvista/pyvista/pull/7033/commits/1f98c47b5b35e9e825ba63c25b4c1a4af60ba280)

The benefits will also be made clear with #7051, since the negative values are used by `color_labels` for the plots

2025-01-04 05:45 UTC, user27182 commented on tests/core/test_imagedata_filters.py
> +    assert poly[BOUNDARY_LABELS].ndim == 2
Should be fixed [2c8363d](https://github.com/pyvista/pyvista/pull/7033/commits/2c8363d3b80d6bd1668977e197b0aa6a792235d5)

2025-01-04 10:24 UTC, tkoyama010 approved these changes
LGTM

2025-01-04 10:26 UTC, merged

2025-01-04 10:30 UTC, tkoyama010 commented
@user27182 I haven't been able to keep track of old pull requests. If you have one that needs review and merging, please send me a review request.