Fix Plot Opacity Array
pyvista/pyvista pull request #906
Opened 2020-09-26 21:57 UTC by akaszynski

### Fix Plot Opacity by Array

Opacity plotting when ``n_colors`` is specified is broken as reported by https://github.com/pyvista/pyvista-support/issues/251.  This fixes the ``n_colors`` argument.

The first issue as noted by that issue is that opacity is normalized internally, which I feel is non-idea as it's not possible to have part of the mesh with an opacity of 0.5 and the rest as 1, as normalizing the opacity scalars will cause half the mesh to be hidden and half to be fully visible.  Instead, this PR proposes that the opacity scalars not be normalized and a warning be issued when the scalars are outside the range ``[0, 1]``.

@banesullivan, since you're the one who implemented the opacity by scalars, I'd like your input before overwriting this.

Example Code:
```py
import numpy as np
import pyvista as pv

ellipsoid = pv.ParametricEllipsoid(10, 5, 5)
ellipsoid.point_arrays["color"] = np.linspace(0,10,len(ellipsoid.points))
ellipsoid.point_arrays["opacity"] = np.where(ellipsoid.points[:, 0] > 0, 0.5, 1)

ellipsoid.plot(scalars="color", n_colors=5, opacity="opacity")
```

Before Fix:
![image](https://user-images.githubusercontent.com/11981631/94350941-eb2cf180-0010-11eb-84a5-8b1f05e4d90a.png)

After Fix:
![image](https://user-images.githubusercontent.com/11981631/94350943-f1bb6900-0010-11eb-9ab2-99716a40d1a5.png)

2020-09-28 03:15 UTC, banesullivan commented
Hm. I had originally implemented this to be used such that any scalar array could be mapped to the opacity (hence the normalization). E.g. using a variance field to as the opacity and letting high variance be transparent and low variance be opaque.

I hadn't really needed to use the opacity scalars this way but I see the value. I'd like to test this out a with a few datasets to make sure all is good.... though I'm swamped lately so if you don't hear back from me in a week, go ahead and merge

2020-10-03 02:53 UTC, banesullivan requested changes
These changes are not compatible with the example in the docs: https://docs.pyvista.org/examples/02-plot/opacity.html#opacity-by-array

| master | this branch |
|---|---|
|  ![download](https://user-images.githubusercontent.com/22067021/94981662-3d7a8080-04f1-11eb-842e-58e2d0b54914.png) |  ![download](https://user-images.githubusercontent.com/22067021/94981667-44a18e80-04f1-11eb-8415-11a33964e165.png) |

2020-10-08 15:55 UTC, akaszynski commented
Fixed in 6af20c8

![image](https://user-images.githubusercontent.com/11981631/95483404-66b16b80-094c-11eb-9e74-51339661345d.png)

2020-10-08 22:21 UTC, akaszynski commented
@banesullivan, ready for a re-review.

2020-10-08 23:14 UTC, banesullivan approved these changes

2020-10-08 23:14 UTC, banesullivan commented on examples/02-plot/opacity.py
> +contours['Temperature_var'] /= contours['Temperature_var'].max()
Makes sense, thanks for the clarification here!

2020-10-09 02:50 UTC, merged