Normalize by scale when computing 4x4 transform
pyvista/pyvista pull request #936
Opened 2020-10-08 18:27 UTC by russelldj

### Overview

It is convention that a when using a 4x4 homogeneous transformation matrix, the last element represents an inverse scale. This is described briefly in the third item of section Using homogeneous coordinates on [Wikipedia](https://en.wikipedia.org/wiki/Scaling_(geometry)). This change has been tested locally and it mimics the behavior of other libraries. If the last coordinate is 0, it could induce a division my zero error. 

### Details

- Add scaling to the `transform` method.

2020-10-08 18:28 UTC, russelldj commented
It also failed the following integration test, which appears unrelated. 
`Unexpected failing examples:
/home/david/dev/pyvista/examples/01-filter/gradients.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/david/dev/pyvista/examples/01-filter/gradients.py", line 27, in <module>
    mesh_g = mesh.compute_derivative(scalars="vectors")
AttributeError: 'UniformGrid' object has no attribute 'compute_derivative'
`

2020-10-08 20:47 UTC, akaszynski approved these changes
Good catch.  LGTM

2020-10-08 20:51 UTC, akaszynski requested changes
Actually, would it be possible to normalize the transform matrix first by the scale factor instead?  This could lead to a big speedup when transforming as you won't divide the entire points array by the scaling factor.

Additionally, we might consider implementing a check to see if the scaling factor is zero to avoid zero division (which would just set the array to `np.nan`).

2020-10-09 12:36 UTC, russelldj commented
That makes sense, I'll push that change up shortly. One thing I was thinking about was whether we should have a warning or error for negative scale terms? This will flip all the axis. It could be an intended behavior in some cases, but it might have unintended consequences (weird issues with normals maybe?) or be difficult to debug if done intentionally.

2020-10-09 15:31 UTC, akaszynski commented
> That makes sense, I'll push that change up shortly. One thing I was thinking about was whether we should have a warning or error for negative scale terms? This will flip all the axis. It could be an intended behavior in some cases, but it might have unintended consequences (weird issues with normals maybe?) or be difficult to debug if done intentionally.

Maybe.  Or maybe it's intentional.  I think issuing an error when scaling is 0 makes sense, but a negative scaling might be intentional and it would be annoying to get warnings/errors if someone intended to do that (however rare it might be).

2020-10-13 01:10 UTC, russelldj commented
Sorry for the late push. I added the changes we discussed. I struggled a bit on finding a concise error message and would definitely welcome a better one.

2020-10-13 14:57 UTC, merged